processed 5 tasks

task 1 'run-graphql'. lines 6-28:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "3TtZTUP8Us4DywKkd5bRhXt5N5TTeqna5S8jAPe1dy2v",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "3TtZTUP8Us4DywKkd5bRhXt5N5TTeqna5S8jAPe1dy2v",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "3TtZTUP8Us4DywKkd5bRhXt5N5TTeqna5S8jAPe1dy2v",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "3TtZTUP8Us4DywKkd5bRhXt5N5TTeqna5S8jAPe1dy2v",
      "sequenceNumber": 0
    }
  }
}

task 2 'create-checkpoint'. lines 30-30:
Checkpoint created: 1

task 3 'create-checkpoint'. lines 33-33:
Checkpoint created: 2

task 4 'run-graphql'. lines 36-58:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "3TtZTUP8Us4DywKkd5bRhXt5N5TTeqna5S8jAPe1dy2v",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "9r7GukRFZwNg7PWQU8U2MEP6MBbgdt13xmGmK2U3tqXk",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "3TtZTUP8Us4DywKkd5bRhXt5N5TTeqna5S8jAPe1dy2v",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "9r7GukRFZwNg7PWQU8U2MEP6MBbgdt13xmGmK2U3tqXk",
      "sequenceNumber": 2
    }
  }
}
