processed 5 tasks

task 1 'run-graphql'. lines 6-28:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "rorv6KS6ZGuuKPxpX7kzTXTNHpbXUtEBrMKTim7xhng",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "rorv6KS6ZGuuKPxpX7kzTXTNHpbXUtEBrMKTim7xhng",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "rorv6KS6ZGuuKPxpX7kzTXTNHpbXUtEBrMKTim7xhng",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "rorv6KS6ZGuuKPxpX7kzTXTNHpbXUtEBrMKTim7xhng",
      "sequenceNumber": 0
    }
  }
}

task 2 'create-checkpoint'. lines 30-30:
Checkpoint created: 1

task 3 'create-checkpoint'. lines 33-33:
Checkpoint created: 2

task 4 'run-graphql'. lines 36-58:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "rorv6KS6ZGuuKPxpX7kzTXTNHpbXUtEBrMKTim7xhng",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "HpUbyNNBZgikHgawCwV4Sr7m1gzXaeepE4h2z7pk6kKr",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "rorv6KS6ZGuuKPxpX7kzTXTNHpbXUtEBrMKTim7xhng",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "HpUbyNNBZgikHgawCwV4Sr7m1gzXaeepE4h2z7pk6kKr",
      "sequenceNumber": 2
    }
  }
}
