processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-186:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "5xzrmJnCS8v4ovKvPXETLVdDoeTwLHgpy65CKk5sh5QL",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AJHSTkUtXyhISQrMJJwttDoKqGUitE2t4hrb3ZFCiewbuhM3Z+eNkJdyBuB2PKoSB+68JsY3OAxUFkZABCBakQN/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "PublishTransaction",
                  "modules": [
                    "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                  ],
                  "dependencies": [
                    "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x0000000000000000000000000000000000000000000000000000000000000002"
                  ]
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 0
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "DJcX5JjxZF2NBfUs5G5spP6uNcju9dmaWRpqgLahV4Ah"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-7315600",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x1f42e5c074f7af606ef0f58bd7fbe1f2869f00db0278c7dc996767cc727cac5b",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x1f42e5c074f7af606ef0f58bd7fbe1f2869f00db0278c7dc996767cc727cac5b",
                  "digest": "BedVzKY3KihxUnKkjYRYnAzQdn3PezQVGmqszhxoXjXf"
                }
              },
              {
                "address": "0x5fc33747d99afbe71d1a4704908896640c41d79c097ec472c1b93868ab48a639",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5fc33747d99afbe71d1a4704908896640c41d79c097ec472c1b93868ab48a639",
                  "digest": "ASGzKoTFU6oFf4czT3z9wQLmHzXT245WfaNJpGCUH4cn"
                }
              },
              {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                  "digest": "8sfk1eAgvtAETHkzrbHJGuopV1tErCNiUYXPhS6pdu84"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "5xzrmJnCS8v4ovKvPXETLVdDoeTwLHgpy65CKk5sh5QL"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 188-206:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 208-208:
Checkpoint created: 2

task 6 'run-graphql'. lines 210-373:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "DmwZNRgHFQJ76YhvGsq8z7Qc1jhYkpqJvm28K7qpGfHR",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AHXVX5S9d+mFdd9viwEl2pPiu5iswx5p1c/X00xxeYofID/If8fftRDHJ1woueDc8wBp8JzvK0Ftx9aIou4OrQ1/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "OwnedOrImmutable",
                  "address": "0x5fc33747d99afbe71d1a4704908896640c41d79c097ec472c1b93868ab48a639",
                  "version": 2,
                  "digest": "ASGzKoTFU6oFf4czT3z9wQLmHzXT245WfaNJpGCUH4cn",
                  "object": null
                },
                {
                  "__typename": "Pure",
                  "bytes": "AA=="
                },
                {
                  "__typename": "Pure",
                  "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "module": "package",
                  "functionName": "authorize_upgrade",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Input",
                      "ix": 1
                    },
                    {
                      "__typename": "Input",
                      "ix": 2
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                      },
                      {
                        "repr": "u8"
                      },
                      {
                        "repr": "vector<u8>"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                      }
                    ]
                  }
                },
                {
                  "__typename": "UpgradeTransaction",
                  "modules": [
                    "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                  ],
                  "dependencies": [
                    "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x0000000000000000000000000000000000000000000000000000000000000002"
                  ],
                  "currentPackage": "0x1f42e5c074f7af606ef0f58bd7fbe1f2869f00db0278c7dc996767cc727cac5b",
                  "upgradeTicket": {
                    "__typename": "Result",
                    "cmd": 0,
                    "ix": null
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "module": "package",
                  "functionName": "commit_upgrade",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Result",
                      "cmd": 1,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                      },
                      {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                      }
                    ],
                    "return": []
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": [
              {
                "digest": "DJcX5JjxZF2NBfUs5G5spP6uNcju9dmaWRpqgLahV4Ah"
              },
              {
                "digest": "5xzrmJnCS8v4ovKvPXETLVdDoeTwLHgpy65CKk5sh5QL"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-4993420",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x5fc33747d99afbe71d1a4704908896640c41d79c097ec472c1b93868ab48a639",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5fc33747d99afbe71d1a4704908896640c41d79c097ec472c1b93868ab48a639",
                  "digest": "DyT4dSF1s8zw1NeHLaxTWiXdAb96WcfwQN6yPSnt9DPs"
                }
              },
              {
                "address": "0x800e2b09d89f849b965178b93463c4fe79f591e05c7110c5d6908da9d09ffb6d",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x800e2b09d89f849b965178b93463c4fe79f591e05c7110c5d6908da9d09ffb6d",
                  "digest": "6ytcicLhWDQEMUfNY9gAuvFjUou8E7xHp2RQjrUVDscP"
                }
              },
              {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                  "digest": "7q6BaTtHNEnyDw2dnDGNf33QzZGwzgwsrMoeYhRWU2KS"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "DmwZNRgHFQJ76YhvGsq8z7Qc1jhYkpqJvm28K7qpGfHR"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 375-384:
created: object(7,0), object(7,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 386-386:
Checkpoint created: 3

task 9 'run-graphql'. lines 388-560:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "FsJtfHkWxBFwy7FpE7so7Cpt1Rai6JLZrSJtwkwEMkEY",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AKsmbzJCx7NOLnO9dCfUT7uUWJKgLjhgVtnqYbi6ksTMZ5h+AUbwyzsUitqZfuULNCEt8f/uF0rstnsTqSkEjQp/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "KgAAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "KwAAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "6AMAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "MakeMoveVecTransaction",
                  "type": {
                    "repr": "u64"
                  },
                  "elements": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Input",
                      "ix": 1
                    }
                  ]
                },
                {
                  "__typename": "MakeMoveVecTransaction",
                  "type": {
                    "repr": "u64"
                  },
                  "elements": []
                },
                {
                  "__typename": "SplitCoinsTransaction",
                  "coin": {
                    "__typename": "GasCoin"
                  },
                  "amounts": [
                    {
                      "__typename": "Input",
                      "ix": 2
                    },
                    {
                      "__typename": "Input",
                      "ix": 2
                    }
                  ]
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x800e2b09d89f849b965178b93463c4fe79f591e05c7110c5d6908da9d09ffb6d",
                  "module": "m",
                  "functionName": "new",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "vector<u64>"
                      },
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0x1f42e5c074f7af606ef0f58bd7fbe1f2869f00db0278c7dc996767cc727cac5b::m::Foo"
                      }
                    ]
                  }
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 3,
                      "ix": null
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 3
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x800e2b09d89f849b965178b93463c4fe79f591e05c7110c5d6908da9d09ffb6d",
                  "module": "m",
                  "functionName": "new",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 1,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "vector<u64>"
                      },
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0x1f42e5c074f7af606ef0f58bd7fbe1f2869f00db0278c7dc996767cc727cac5b::m::Foo"
                      }
                    ]
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x800e2b09d89f849b965178b93463c4fe79f591e05c7110c5d6908da9d09ffb6d",
                  "module": "m",
                  "functionName": "burn",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 5,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "0x1f42e5c074f7af606ef0f58bd7fbe1f2869f00db0278c7dc996767cc727cac5b::m::Foo"
                      }
                    ],
                    "return": []
                  }
                },
                {
                  "__typename": "MergeCoinsTransaction",
                  "coin": {
                    "__typename": "Result",
                    "cmd": 2,
                    "ix": 0
                  },
                  "coins": [
                    {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 1
                    }
                  ]
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 3
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 4,
            "dependencies": [
              {
                "digest": "DmwZNRgHFQJ76YhvGsq8z7Qc1jhYkpqJvm28K7qpGfHR"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-3350680",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x05ec72560b154ad886c06d42a1b57044f75695046560edf85f3dd19adf43e4d1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x05ec72560b154ad886c06d42a1b57044f75695046560edf85f3dd19adf43e4d1",
                  "digest": "GtAgNUxCkKDQqjQ4sBDcRoecMuY3Gi92d5dy7ZQU85bY",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x05ec72560b154ad886c06d42a1b57044f75695046560edf85f3dd19adf43e4d1",
                        "balance": {
                          "value": "2000"
                        }
                      }
                    }
                  }
                }
              },
              {
                "address": "0xbf199f4cdb7fa6471cb50de9be0b21e7e56b064d5a7431d3f90ccd987b40c7d1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xbf199f4cdb7fa6471cb50de9be0b21e7e56b064d5a7431d3f90ccd987b40c7d1",
                  "digest": "FPA42Uz1WKtoJeFJSPtqDsddp1NaBvdsj16jSDkcUvSf",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x1f42e5c074f7af606ef0f58bd7fbe1f2869f00db0278c7dc996767cc727cac5b::m::Foo"
                      },
                      "json": {
                        "id": "0xbf199f4cdb7fa6471cb50de9be0b21e7e56b064d5a7431d3f90ccd987b40c7d1",
                        "xs": [
                          "42",
                          "43"
                        ]
                      }
                    }
                  }
                }
              },
              {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                  "digest": "FMcYhP619pR9XG8bP6gFzZRy9747e6inqYqatEfC3GoB",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                        "balance": {
                          "value": "299999984338300"
                        }
                      }
                    }
                  }
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "FsJtfHkWxBFwy7FpE7so7Cpt1Rai6JLZrSJtwkwEMkEY"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 10 'programmable'. lines 562-563:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 11 'create-checkpoint'. lines 565-565:
Checkpoint created: 4

task 12 'run-graphql'. lines 567-730:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "6kqD72ortGXrabuRb5patGAicAZGafNPgr33h91fyBje",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "ACa2VqdG88cqyP+tE5NMeIX1r0Hn0o5tiVwfizaIhKC4gtYNa/t+WmP3+DW2CpufJf/Th6aivHSgFhNdZlvIZAp/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "6AMAAAAAAAA="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "SplitCoinsTransaction",
                  "coin": {
                    "__typename": "GasCoin"
                  },
                  "amounts": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    }
                  ]
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 5,
            "dependencies": [
              {
                "digest": "FsJtfHkWxBFwy7FpE7so7Cpt1Rai6JLZrSJtwkwEMkEY"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-1009880",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65",
                  "digest": "DjDHMWxCZJ7pZrgu8xbESFghievEQqjVJZAaEuUNhPdF"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xdfa2542dbaab81b77d8f013f2d5527ac361f9881bb29f53e27dbb87eac26cc65"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "6kqD72ortGXrabuRb5patGAicAZGafNPgr33h91fyBje"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
