processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-186:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "6mXk8U4q1m6HcAkzc6LuZmAVQ7wbYqNAoXNuKUiSPU3u",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "ABXOKS9xeqwI1Z3xUDmdTp05QWmhZ2bfl5TRkCQwLQPtddMHroDW9LbhvYa7ILrBb7iUEjVIdSGKzQ0juZYuqgx/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "PublishTransaction",
                  "modules": [
                    "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                  ],
                  "dependencies": [
                    "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x0000000000000000000000000000000000000000000000000000000000000002"
                  ]
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 0
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "EFVkoZiYZH4zuwpkMMW15BiZbrntupkdP2LTcXGuvx62"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-7315600",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x5bb321a70d8b716383cc3c387967a290c4e08db0b5e337410010e03e90b8a371",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5bb321a70d8b716383cc3c387967a290c4e08db0b5e337410010e03e90b8a371",
                  "digest": "HpAW4jUiBhmEkWmZTugBFShpaL5e7n3szVtRXBV1MRfB"
                }
              },
              {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                  "digest": "3Km4xwzeqWALgmFXnVDSbLyTRGC1EE7ovZYZewmvzct4"
                }
              },
              {
                "address": "0xec4ab6246595e01397b1c0487b4b82e84fd20efe65820fc1411a8e94893ca21c",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xec4ab6246595e01397b1c0487b4b82e84fd20efe65820fc1411a8e94893ca21c",
                  "digest": "5tfwQjxmH1CtquphWCUPAt2zkWNziPGMBh1a984R6k7B"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "6mXk8U4q1m6HcAkzc6LuZmAVQ7wbYqNAoXNuKUiSPU3u"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 188-206:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 208-208:
Checkpoint created: 2

task 6 'run-graphql'. lines 210-373:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "HbPTsg5kxVVu5MxrWYfB3JJjuuZVQZbWUpS79CTy4Dun",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AI6KtzX3e4uCG4my/tgUMXuJdFPXltagytbGsOCzAKxU3ETS56mhUVnFgnQL16gDNa68OPChKHmJqOiHoO5B2wx/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "OwnedOrImmutable",
                  "address": "0x5bb321a70d8b716383cc3c387967a290c4e08db0b5e337410010e03e90b8a371",
                  "version": 2,
                  "digest": "HpAW4jUiBhmEkWmZTugBFShpaL5e7n3szVtRXBV1MRfB",
                  "object": null
                },
                {
                  "__typename": "Pure",
                  "bytes": "AA=="
                },
                {
                  "__typename": "Pure",
                  "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "module": "package",
                  "functionName": "authorize_upgrade",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Input",
                      "ix": 1
                    },
                    {
                      "__typename": "Input",
                      "ix": 2
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                      },
                      {
                        "repr": "u8"
                      },
                      {
                        "repr": "vector<u8>"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                      }
                    ]
                  }
                },
                {
                  "__typename": "UpgradeTransaction",
                  "modules": [
                    "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                  ],
                  "dependencies": [
                    "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x0000000000000000000000000000000000000000000000000000000000000002"
                  ],
                  "currentPackage": "0xec4ab6246595e01397b1c0487b4b82e84fd20efe65820fc1411a8e94893ca21c",
                  "upgradeTicket": {
                    "__typename": "Result",
                    "cmd": 0,
                    "ix": null
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "module": "package",
                  "functionName": "commit_upgrade",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Result",
                      "cmd": 1,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                      },
                      {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                      }
                    ],
                    "return": []
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": [
              {
                "digest": "EFVkoZiYZH4zuwpkMMW15BiZbrntupkdP2LTcXGuvx62"
              },
              {
                "digest": "6mXk8U4q1m6HcAkzc6LuZmAVQ7wbYqNAoXNuKUiSPU3u"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-4993420",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x5bb321a70d8b716383cc3c387967a290c4e08db0b5e337410010e03e90b8a371",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5bb321a70d8b716383cc3c387967a290c4e08db0b5e337410010e03e90b8a371",
                  "digest": "Ur5z5HzhNUnWJSnfkomUb3qKD4MhQ31pnCGrZKP9uH1"
                }
              },
              {
                "address": "0x5f9a3af09a231c3b1002d0e0f96e95f80e5a7d8574036872c5dc78eea4b23e67",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5f9a3af09a231c3b1002d0e0f96e95f80e5a7d8574036872c5dc78eea4b23e67",
                  "digest": "FW5n5pRULsJjFVGt2VbVP39cKiVXF78wVV2pKHQQp8Dv"
                }
              },
              {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                  "digest": "HtQHXCAUuT7k1EMyQbsgZR2tJNbUpbHooqDjTufChwGC"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "HbPTsg5kxVVu5MxrWYfB3JJjuuZVQZbWUpS79CTy4Dun"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 375-384:
created: object(7,0), object(7,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 386-386:
Checkpoint created: 3

task 9 'run-graphql'. lines 388-560:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "4zqYB47McJe928NU3Yj6HHZhQirWum7anCdJawgJxrQv",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AGsOiUJwT22Per4hCdfSXEc9VTZxRfhevekWgoU1H+kXLCxxIEjcR0UnKQhEDiIX1CsgVL2qWe2el0cN+N6gZgN/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "KgAAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "KwAAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "6AMAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "MakeMoveVecTransaction",
                  "type": {
                    "repr": "u64"
                  },
                  "elements": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Input",
                      "ix": 1
                    }
                  ]
                },
                {
                  "__typename": "MakeMoveVecTransaction",
                  "type": {
                    "repr": "u64"
                  },
                  "elements": []
                },
                {
                  "__typename": "SplitCoinsTransaction",
                  "coin": {
                    "__typename": "GasCoin"
                  },
                  "amounts": [
                    {
                      "__typename": "Input",
                      "ix": 2
                    },
                    {
                      "__typename": "Input",
                      "ix": 2
                    }
                  ]
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x5f9a3af09a231c3b1002d0e0f96e95f80e5a7d8574036872c5dc78eea4b23e67",
                  "module": "m",
                  "functionName": "new",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "vector<u64>"
                      },
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0xec4ab6246595e01397b1c0487b4b82e84fd20efe65820fc1411a8e94893ca21c::m::Foo"
                      }
                    ]
                  }
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 3,
                      "ix": null
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 3
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x5f9a3af09a231c3b1002d0e0f96e95f80e5a7d8574036872c5dc78eea4b23e67",
                  "module": "m",
                  "functionName": "new",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 1,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "vector<u64>"
                      },
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0xec4ab6246595e01397b1c0487b4b82e84fd20efe65820fc1411a8e94893ca21c::m::Foo"
                      }
                    ]
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x5f9a3af09a231c3b1002d0e0f96e95f80e5a7d8574036872c5dc78eea4b23e67",
                  "module": "m",
                  "functionName": "burn",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 5,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "0xec4ab6246595e01397b1c0487b4b82e84fd20efe65820fc1411a8e94893ca21c::m::Foo"
                      }
                    ],
                    "return": []
                  }
                },
                {
                  "__typename": "MergeCoinsTransaction",
                  "coin": {
                    "__typename": "Result",
                    "cmd": 2,
                    "ix": 0
                  },
                  "coins": [
                    {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 1
                    }
                  ]
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 3
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 4,
            "dependencies": [
              {
                "digest": "HbPTsg5kxVVu5MxrWYfB3JJjuuZVQZbWUpS79CTy4Dun"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-3350680",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x05455931c553b42fbe0c670899d0a2e794deab5a4055cb65f7fce298dfe01c56",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x05455931c553b42fbe0c670899d0a2e794deab5a4055cb65f7fce298dfe01c56",
                  "digest": "Ai3a227om1jkmibekjc9tvDbcQEmNVhFwC3h1Q13JBAW",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x05455931c553b42fbe0c670899d0a2e794deab5a4055cb65f7fce298dfe01c56",
                        "balance": {
                          "value": "2000"
                        }
                      }
                    }
                  }
                }
              },
              {
                "address": "0x759bf23a13fa3040e829f2c970c641a9b33d40470c522c78441003428025809a",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x759bf23a13fa3040e829f2c970c641a9b33d40470c522c78441003428025809a",
                  "digest": "CyTGHLjyobcGuaWjxUHhaMNesSLYBnrM6JYxxUbyuYwt",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0xec4ab6246595e01397b1c0487b4b82e84fd20efe65820fc1411a8e94893ca21c::m::Foo"
                      },
                      "json": {
                        "id": "0x759bf23a13fa3040e829f2c970c641a9b33d40470c522c78441003428025809a",
                        "xs": [
                          "42",
                          "43"
                        ]
                      }
                    }
                  }
                }
              },
              {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                  "digest": "BjW4hzQUdu31CxVMEycrTBGb9Dn4K12F1kRTFsthxqng",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                        "balance": {
                          "value": "299999984338300"
                        }
                      }
                    }
                  }
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "4zqYB47McJe928NU3Yj6HHZhQirWum7anCdJawgJxrQv"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 10 'programmable'. lines 562-563:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 11 'create-checkpoint'. lines 565-565:
Checkpoint created: 4

task 12 'run-graphql'. lines 567-730:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "4wCxySXXS1JDipgXzCDT7dnEjTTHfBgQF91PS6oCLJTx",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AGAHJiULlVzD2y9gErlHevUt4LJtmDTxhyfFinXdJvcGR6T19AT0fY6YaePU0UuFUTGzySI9NggDo0w8QfLIIQ1/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "6AMAAAAAAAA="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "SplitCoinsTransaction",
                  "coin": {
                    "__typename": "GasCoin"
                  },
                  "amounts": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    }
                  ]
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 5,
            "dependencies": [
              {
                "digest": "4zqYB47McJe928NU3Yj6HHZhQirWum7anCdJawgJxrQv"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-1009880",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42",
                  "digest": "Ej1DdYA3YLXYzaMoXbwyNjTgYVoLmam9NxoTgUJwwPe5"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xc6533c9a2297da7851fc85254419652ee930de2975d6a8c4921638b5b2b53a42"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "4wCxySXXS1JDipgXzCDT7dnEjTTHfBgQF91PS6oCLJTx"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
