processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-186:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "5nTA7nBSSjPsVF8VHjSc6xYSvb4y6qh4TNuHqR3vFion",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AMdh7yY9eVgb7IbfrICeCk1tvjtfntS9dOK8uX1KRtkmdzjgl0vkxY3M2XIVF+DPloK26GBCDAYR1v1QUd+CTQB/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "PublishTransaction",
                  "modules": [
                    "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                  ],
                  "dependencies": [
                    "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x0000000000000000000000000000000000000000000000000000000000000002"
                  ]
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 0
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "7ZLZYUk8m6fh5JBdNYoCfjEc53r2DdYKMBmB8Y11UE3o"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-7315600",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x1617f2667e5c89dcefa30129432607a706e7e44668ecf1e9047a348d8f387fd0",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x1617f2667e5c89dcefa30129432607a706e7e44668ecf1e9047a348d8f387fd0",
                  "digest": "FU4L1pa3DnWT48JRabGyPf1zcbqkkkgaFaCNJLyckHee"
                }
              },
              {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                  "digest": "6e4L9z1qdoYwXLrKh1stKKpsCpVPzqLER6hnLyW5Zfxw"
                }
              },
              {
                "address": "0xe57b3f391341166fedb046a22d1f1f541b2c91ab6d0ffe41a5398d6733e20923",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xe57b3f391341166fedb046a22d1f1f541b2c91ab6d0ffe41a5398d6733e20923",
                  "digest": "3oC2sM5xfC7fTDUvLkH67LHZ4hxJ3aQb2opY5T11iDXV"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "5nTA7nBSSjPsVF8VHjSc6xYSvb4y6qh4TNuHqR3vFion"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 188-206:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 208-208:
Checkpoint created: 2

task 6 'run-graphql'. lines 210-373:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "76eCWyM8UBxVs6ZjswVcrMTgywjic7ooyLbmsRiRTvi",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AL6O2yDyaRiwIrCPc6ma0ukIFpKlPFsp1VkC9BCwZKbqEqbeTfPF4NIzqcquJKjz0ZKP0gPi2YSPfu0RwRLeSAN/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "OwnedOrImmutable",
                  "address": "0x1617f2667e5c89dcefa30129432607a706e7e44668ecf1e9047a348d8f387fd0",
                  "version": 2,
                  "digest": "FU4L1pa3DnWT48JRabGyPf1zcbqkkkgaFaCNJLyckHee",
                  "object": null
                },
                {
                  "__typename": "Pure",
                  "bytes": "AA=="
                },
                {
                  "__typename": "Pure",
                  "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "module": "package",
                  "functionName": "authorize_upgrade",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Input",
                      "ix": 1
                    },
                    {
                      "__typename": "Input",
                      "ix": 2
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                      },
                      {
                        "repr": "u8"
                      },
                      {
                        "repr": "vector<u8>"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                      }
                    ]
                  }
                },
                {
                  "__typename": "UpgradeTransaction",
                  "modules": [
                    "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                  ],
                  "dependencies": [
                    "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x0000000000000000000000000000000000000000000000000000000000000002"
                  ],
                  "currentPackage": "0xe57b3f391341166fedb046a22d1f1f541b2c91ab6d0ffe41a5398d6733e20923",
                  "upgradeTicket": {
                    "__typename": "Result",
                    "cmd": 0,
                    "ix": null
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "module": "package",
                  "functionName": "commit_upgrade",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Result",
                      "cmd": 1,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                      },
                      {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                      }
                    ],
                    "return": []
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": [
              {
                "digest": "7ZLZYUk8m6fh5JBdNYoCfjEc53r2DdYKMBmB8Y11UE3o"
              },
              {
                "digest": "5nTA7nBSSjPsVF8VHjSc6xYSvb4y6qh4TNuHqR3vFion"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-4993420",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x1617f2667e5c89dcefa30129432607a706e7e44668ecf1e9047a348d8f387fd0",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x1617f2667e5c89dcefa30129432607a706e7e44668ecf1e9047a348d8f387fd0",
                  "digest": "79HbQiTa1U4wsTPKpR5de18JwDLPMD8rj9979rLnEvTA"
                }
              },
              {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                  "digest": "Ht36TrQsQbzGbbXXHXx4guN6mRGZRVM2zF3UGhEsLJ99"
                }
              },
              {
                "address": "0xf46af308f35d60b77de80d0615c5292ec96153da068abac16fc73e04941e6928",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xf46af308f35d60b77de80d0615c5292ec96153da068abac16fc73e04941e6928",
                  "digest": "8RRuPpPjQp5iE2BJRPTzw5YXSv3ci32PU5ZuMBQVsiBj"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "76eCWyM8UBxVs6ZjswVcrMTgywjic7ooyLbmsRiRTvi"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 375-384:
created: object(7,0), object(7,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 386-386:
Checkpoint created: 3

task 9 'run-graphql'. lines 388-560:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "7nMQGNYkAcgXa5uDxpBQjrhGvToXhnU1vG7nHGT5DyRg",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AJolwq+3eAvVZH0RaOsvVmWduzf/AF8nl22jcStx6J8j6DK0COvRMxKVqKvPYiGZj1+pdQ8lXWnzB74gKs002wJ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "KgAAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "KwAAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "6AMAAAAAAAA="
                },
                {
                  "__typename": "Pure",
                  "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "MakeMoveVecTransaction",
                  "type": {
                    "repr": "u64"
                  },
                  "elements": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    },
                    {
                      "__typename": "Input",
                      "ix": 1
                    }
                  ]
                },
                {
                  "__typename": "MakeMoveVecTransaction",
                  "type": {
                    "repr": "u64"
                  },
                  "elements": []
                },
                {
                  "__typename": "SplitCoinsTransaction",
                  "coin": {
                    "__typename": "GasCoin"
                  },
                  "amounts": [
                    {
                      "__typename": "Input",
                      "ix": 2
                    },
                    {
                      "__typename": "Input",
                      "ix": 2
                    }
                  ]
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0xf46af308f35d60b77de80d0615c5292ec96153da068abac16fc73e04941e6928",
                  "module": "m",
                  "functionName": "new",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "vector<u64>"
                      },
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0xe57b3f391341166fedb046a22d1f1f541b2c91ab6d0ffe41a5398d6733e20923::m::Foo"
                      }
                    ]
                  }
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 3,
                      "ix": null
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 3
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0xf46af308f35d60b77de80d0615c5292ec96153da068abac16fc73e04941e6928",
                  "module": "m",
                  "functionName": "new",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 1,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "vector<u64>"
                      },
                      {
                        "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                      }
                    ],
                    "return": [
                      {
                        "repr": "0xe57b3f391341166fedb046a22d1f1f541b2c91ab6d0ffe41a5398d6733e20923::m::Foo"
                      }
                    ]
                  }
                },
                {
                  "__typename": "MoveCallTransaction",
                  "package": "0xf46af308f35d60b77de80d0615c5292ec96153da068abac16fc73e04941e6928",
                  "module": "m",
                  "functionName": "burn",
                  "typeArguments": [],
                  "arguments": [
                    {
                      "__typename": "Result",
                      "cmd": 5,
                      "ix": null
                    }
                  ],
                  "function": {
                    "isEntry": false,
                    "typeParameters": [],
                    "parameters": [
                      {
                        "repr": "0xe57b3f391341166fedb046a22d1f1f541b2c91ab6d0ffe41a5398d6733e20923::m::Foo"
                      }
                    ],
                    "return": []
                  }
                },
                {
                  "__typename": "MergeCoinsTransaction",
                  "coin": {
                    "__typename": "Result",
                    "cmd": 2,
                    "ix": 0
                  },
                  "coins": [
                    {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 1
                    }
                  ]
                },
                {
                  "__typename": "TransferObjectsTransaction",
                  "inputs": [
                    {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    }
                  ],
                  "address": {
                    "__typename": "Input",
                    "ix": 3
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 4,
            "dependencies": [
              {
                "digest": "76eCWyM8UBxVs6ZjswVcrMTgywjic7ooyLbmsRiRTvi"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-3350680",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                  "digest": "4NBaiFJ7GJuvfUupmexxK61bnjFSsWR9wY4NnjtJDNzR",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                        "balance": {
                          "value": "299999984338300"
                        }
                      }
                    }
                  }
                }
              },
              {
                "address": "0x65bb478d2a2ed1cf14b0bc5a51c6f9ba450f71380f466984968afb690ea737e9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x65bb478d2a2ed1cf14b0bc5a51c6f9ba450f71380f466984968afb690ea737e9",
                  "digest": "4D1jCBqHyfSD6oronnkFM6KafymRD1X6ZEwhuFFrV8Zy",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0xe57b3f391341166fedb046a22d1f1f541b2c91ab6d0ffe41a5398d6733e20923::m::Foo"
                      },
                      "json": {
                        "id": "0x65bb478d2a2ed1cf14b0bc5a51c6f9ba450f71380f466984968afb690ea737e9",
                        "xs": [
                          "42",
                          "43"
                        ]
                      }
                    }
                  }
                }
              },
              {
                "address": "0xaadf5d6bbf82fc5ee9dbd3dfad76cca519f7946699777dfafe49944458611979",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xaadf5d6bbf82fc5ee9dbd3dfad76cca519f7946699777dfafe49944458611979",
                  "digest": "rsv9wBXsBQAxX8BT5ShtjC85zTsqDtrqpoU71yE9PNc",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xaadf5d6bbf82fc5ee9dbd3dfad76cca519f7946699777dfafe49944458611979",
                        "balance": {
                          "value": "2000"
                        }
                      }
                    }
                  }
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "7nMQGNYkAcgXa5uDxpBQjrhGvToXhnU1vG7nHGT5DyRg"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 10 'programmable'. lines 562-563:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 11 'create-checkpoint'. lines 565-565:
Checkpoint created: 4

task 12 'run-graphql'. lines 567-730:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "BqUHTbwtW4ziMNtvGp49fxnGNeCeRF2f9vUZRjSbXP7z",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AGS091FwPXZ3LakIu/Vl+rpn9REHnnyhCkJotQH8XX7dVwHqOqQCrFaffhdW19aAtKkDRYJ/7v4CJ4et0H1y/Ap/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputConnection": {
              "nodes": [
                {
                  "__typename": "Pure",
                  "bytes": "6AMAAAAAAAA="
                }
              ]
            },
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "SplitCoinsTransaction",
                  "coin": {
                    "__typename": "GasCoin"
                  },
                  "amounts": [
                    {
                      "__typename": "Input",
                      "ix": 0
                    }
                  ]
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 5,
            "dependencies": [
              {
                "digest": "7nMQGNYkAcgXa5uDxpBQjrhGvToXhnU1vG7nHGT5DyRg"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-1009880",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39",
                  "digest": "FU5AgeBoXrDvuG7zEihQeLXr4L6U87au12bxwBiVLGZx"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0x32cc3d298f1ca4cd00c60974fd11471b3fc3436921265f4abe3a16a9b23c6e39"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "BqUHTbwtW4ziMNtvGp49fxnGNeCeRF2f9vUZRjSbXP7z"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
