processed 7 tasks

task 1 'publish'. lines 6-26:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 28-29:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'programmable'. lines 31-32:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 4 'programmable'. lines 34-36:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 5 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 6 'run-graphql'. lines 40-85:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactionConnection": {
              "nodes": [
                {
                  "package": "0xfc2ab664a7ac37f0392a53d8cbb99a2c1b3264609a85914003082a8ace38d0a2",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0xfc2ab664a7ac37f0392a53d8cbb99a2c1b3264609a85914003082a8ace38d0a2",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": []
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactionConnection": {
              "nodes": [
                {
                  "package": "0xfc2ab664a7ac37f0392a53d8cbb99a2c1b3264609a85914003082a8ace38d0a2",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": []
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactionConnection": {
              "nodes": [
                {
                  "package": "0xfc2ab664a7ac37f0392a53d8cbb99a2c1b3264609a85914003082a8ace38d0a2",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": [
              {
                "__typename": "SharedObjectRead",
                "address": "0x6a42be54d4afb69c5072bd5dcc7c634162a67e5b42846622b24c65e9ac7cfd1c",
                "version": 2,
                "digest": "7wv8Q1R4vRDkbURattQowmPiVSFDGf4LqMPN7edqpUT7",
                "object": null
              }
            ]
          }
        }
      ]
    }
  }
}
