processed 7 tasks

task 1 'publish'. lines 6-26:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 28-29:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'programmable'. lines 31-32:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 4 'programmable'. lines 34-36:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 5 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 6 'run-graphql'. lines 40-85:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactionConnection": {
              "nodes": [
                {
                  "package": "0x7d0cec34626e513b82b749549d8baf60b920fce66ad4b42aee6ea34dc92818a1",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0x7d0cec34626e513b82b749549d8baf60b920fce66ad4b42aee6ea34dc92818a1",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": []
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactionConnection": {
              "nodes": [
                {
                  "package": "0x7d0cec34626e513b82b749549d8baf60b920fce66ad4b42aee6ea34dc92818a1",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": []
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactionConnection": {
              "nodes": [
                {
                  "package": "0x7d0cec34626e513b82b749549d8baf60b920fce66ad4b42aee6ea34dc92818a1",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": [
              {
                "__typename": "SharedObjectRead",
                "address": "0xfb5038846480537f12ddce2d0fbded6e57c1ca4a6f94040f5086a6daa0542cc8",
                "version": 2,
                "digest": "9iE4LVdXLiLFPQb6YZjyLgyv2zUdWy6iCW4fDn6t5L67",
                "object": null
              }
            ]
          }
        }
      ]
    }
  }
}
