processed 8 tasks

task 1 'run-graphql'. lines 8-90:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "7LapPXWc3T9z1TvVgUtxd8TPu334uZNes4bzzDjroRgL",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objectConnection": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "ascii"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bit_vector"
                        },
                        {
                          "name": "debug"
                        },
                        {
                          "name": "fixed_point32"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "option"
                        },
                        {
                          "name": "string"
                        },
                        {
                          "name": "type_name"
                        },
                        {
                          "name": "vector"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "authenticator_state"
                        },
                        {
                          "name": "bag"
                        },
                        {
                          "name": "balance"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bls12381"
                        },
                        {
                          "name": "borrow"
                        },
                        {
                          "name": "clock"
                        },
                        {
                          "name": "coin"
                        },
                        {
                          "name": "display"
                        },
                        {
                          "name": "dynamic_field"
                        },
                        {
                          "name": "dynamic_object_field"
                        },
                        {
                          "name": "ecdsa_k1"
                        },
                        {
                          "name": "ecdsa_r1"
                        },
                        {
                          "name": "ecvrf"
                        },
                        {
                          "name": "ed25519"
                        },
                        {
                          "name": "event"
                        },
                        {
                          "name": "groth16"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "hex"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "genesis"
                        },
                        {
                          "name": "stake_subsidy"
                        },
                        {
                          "name": "staking_pool"
                        },
                        {
                          "name": "storage_fund"
                        },
                        {
                          "name": "sui_system"
                        },
                        {
                          "name": "sui_system_state_inner"
                        },
                        {
                          "name": "validator"
                        },
                        {
                          "name": "validator_cap"
                        },
                        {
                          "name": "validator_set"
                        },
                        {
                          "name": "validator_wrapper"
                        },
                        {
                          "name": "voting_power"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                        "timestamp_ms": "0"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                        "inner": {
                          "id": "0xfe9b35a1a0015ed09057a6acd1431c0d77b2e3c35bcb5bb5e7ddaa1f0d0bc469",
                          "version": "1"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "bridge"
                        },
                        {
                          "name": "btc"
                        },
                        {
                          "name": "chain_ids"
                        },
                        {
                          "name": "committee"
                        },
                        {
                          "name": "eth"
                        },
                        {
                          "name": "message"
                        },
                        {
                          "name": "message_types"
                        },
                        {
                          "name": "treasury"
                        },
                        {
                          "name": "usdc"
                        },
                        {
                          "name": "usdt"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "clob"
                        },
                        {
                          "name": "clob_v2"
                        },
                        {
                          "name": "critbit"
                        },
                        {
                          "name": "custodian"
                        },
                        {
                          "name": "custodian_v2"
                        },
                        {
                          "name": "math"
                        },
                        {
                          "name": "order_query"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x367c7571f419221de15a50ed99a1b7b24bdb520a2bfce9792e85a3acda0e94e8",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x367c7571f419221de15a50ed99a1b7b24bdb520a2bfce9792e85a3acda0e94e8",
                        "balance": {
                          "value": "30000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x3d81b8cd6c41269dc5fbe0191492d5512af7921d3323aeb42cdc74566bd4fd5f",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                      },
                      "json": {
                        "id": "0x3d81b8cd6c41269dc5fbe0191492d5512af7921d3323aeb42cdc74566bd4fd5f",
                        "authorizer_validator_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x4852e90be0c9247073025fc4f3ec785de21642af9be7dc0089e6a917441f9cd0",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                      },
                      "json": {
                        "id": "0x4852e90be0c9247073025fc4f3ec785de21642af9be7dc0089e6a917441f9cd0",
                        "pool_id": {
                          "bytes": "0xa85444a8e6d33aee28cc4348423dc68ee2d180e50f6a057640534cae3ab52247"
                        },
                        "stake_activation_epoch": "0",
                        "principal": {
                          "value": "20000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SuiSystemStateInner>"
                      },
                      "json": {
                        "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                        "name": "1",
                        "value": {
                          "epoch": "0",
                          "protocol_version": "32",
                          "system_state_version": "1",
                          "validators": {
                            "total_stake": "20000000000000000",
                            "active_validators": [
                              {
                                "metadata": {
                                  "sui_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244",
                                  "protocol_pubkey_bytes": [
                                    181,
                                    204,
                                    219,
                                    247,
                                    152,
                                    28,
                                    246,
                                    166,
                                    166,
                                    55,
                                    97,
                                    206,
                                    205,
                                    200,
                                    164,
                                    209,
                                    239,
                                    197,
                                    175,
                                    237,
                                    254,
                                    42,
                                    204,
                                    57,
                                    23,
                                    77,
                                    4,
                                    13,
                                    248,
                                    229,
                                    243,
                                    165,
                                    113,
                                    150,
                                    21,
                                    63,
                                    67,
                                    83,
                                    57,
                                    18,
                                    166,
                                    137,
                                    44,
                                    248,
                                    183,
                                    244,
                                    122,
                                    36,
                                    4,
                                    77,
                                    194,
                                    217,
                                    26,
                                    5,
                                    133,
                                    238,
                                    76,
                                    132,
                                    112,
                                    77,
                                    62,
                                    149,
                                    117,
                                    58,
                                    29,
                                    178,
                                    172,
                                    249,
                                    17,
                                    179,
                                    207,
                                    213,
                                    199,
                                    243,
                                    162,
                                    152,
                                    239,
                                    166,
                                    169,
                                    17,
                                    254,
                                    52,
                                    86,
                                    24,
                                    220,
                                    6,
                                    57,
                                    176,
                                    195,
                                    246,
                                    167,
                                    168,
                                    199,
                                    37,
                                    41,
                                    240
                                  ],
                                  "network_pubkey_bytes": [
                                    222,
                                    193,
                                    56,
                                    253,
                                    223,
                                    140,
                                    108,
                                    228,
                                    161,
                                    246,
                                    151,
                                    172,
                                    42,
                                    190,
                                    219,
                                    243,
                                    212,
                                    210,
                                    59,
                                    152,
                                    5,
                                    6,
                                    236,
                                    134,
                                    82,
                                    53,
                                    90,
                                    224,
                                    105,
                                    93,
                                    152,
                                    85
                                  ],
                                  "worker_pubkey_bytes": [
                                    172,
                                    116,
                                    152,
                                    220,
                                    228,
                                    127,
                                    173,
                                    148,
                                    84,
                                    44,
                                    112,
                                    162,
                                    74,
                                    125,
                                    50,
                                    95,
                                    124,
                                    147,
                                    55,
                                    36,
                                    241,
                                    143,
                                    223,
                                    60,
                                    129,
                                    224,
                                    221,
                                    102,
                                    15,
                                    35,
                                    217,
                                    101
                                  ],
                                  "proof_of_possession": [
                                    128,
                                    107,
                                    74,
                                    121,
                                    76,
                                    94,
                                    1,
                                    108,
                                    22,
                                    203,
                                    69,
                                    136,
                                    24,
                                    193,
                                    194,
                                    47,
                                    140,
                                    0,
                                    140,
                                    222,
                                    97,
                                    14,
                                    177,
                                    180,
                                    60,
                                    215,
                                    201,
                                    205,
                                    116,
                                    217,
                                    249,
                                    252,
                                    64,
                                    249,
                                    177,
                                    121,
                                    185,
                                    95,
                                    201,
                                    175,
                                    255,
                                    44,
                                    236,
                                    83,
                                    92,
                                    26,
                                    136,
                                    38
                                  ],
                                  "name": "validator-0",
                                  "description": "",
                                  "image_url": {
                                    "url": ""
                                  },
                                  "project_url": {
                                    "url": ""
                                  },
                                  "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                  "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                  "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                  "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                  "next_epoch_protocol_pubkey_bytes": null,
                                  "next_epoch_proof_of_possession": null,
                                  "next_epoch_network_pubkey_bytes": null,
                                  "next_epoch_worker_pubkey_bytes": null,
                                  "next_epoch_net_address": null,
                                  "next_epoch_p2p_address": null,
                                  "next_epoch_primary_address": null,
                                  "next_epoch_worker_address": null,
                                  "extra_fields": {
                                    "id": "0x1540a71082fadcc32090171423a56dc2bd20f415ade06ecf37f5d83c46b8a5cb",
                                    "size": "0"
                                  }
                                },
                                "voting_power": "10000",
                                "operation_cap_id": {
                                  "bytes": "0x3d81b8cd6c41269dc5fbe0191492d5512af7921d3323aeb42cdc74566bd4fd5f"
                                },
                                "gas_price": "1000",
                                "staking_pool": {
                                  "id": "0xa85444a8e6d33aee28cc4348423dc68ee2d180e50f6a057640534cae3ab52247",
                                  "activation_epoch": "0",
                                  "deactivation_epoch": null,
                                  "sui_balance": "20000000000000000",
                                  "rewards_pool": {
                                    "value": "0"
                                  },
                                  "pool_token_balance": "20000000000000000",
                                  "exchange_rates": {
                                    "id": "0x3cec88d32103832663d240808779b2166597fea18346f7c369387a0d89b79c7d",
                                    "size": "1"
                                  },
                                  "pending_stake": "0",
                                  "pending_total_sui_withdraw": "0",
                                  "pending_pool_token_withdraw": "0",
                                  "extra_fields": {
                                    "id": "0xa3f82585f81e6587854f95045ef68ca29b462792d1a36619d9a3ede94c4ed2aa",
                                    "size": "0"
                                  }
                                },
                                "commission_rate": "200",
                                "next_epoch_stake": "20000000000000000",
                                "next_epoch_gas_price": "1000",
                                "next_epoch_commission_rate": "200",
                                "extra_fields": {
                                  "id": "0xc122427511ba31c606528236b1f44351f43ed2f976b1adf5dd6600f8faeea321",
                                  "size": "0"
                                }
                              }
                            ],
                            "pending_active_validators": {
                              "contents": {
                                "id": "0xf86c2b14e12697796695d466c05b5dc89950b46626f013070846a15e166442b4",
                                "size": "0"
                              }
                            },
                            "pending_removals": [],
                            "staking_pool_mappings": {
                              "id": "0x06897484bb49da3596dc99fbbb0c3e6b526b79d60c893451e4570617e6cb6fa2",
                              "size": "1"
                            },
                            "inactive_validators": {
                              "id": "0xff617d17fbbd31af460f373389e0a0a9191b54a6aec897ac7b52a338997c0439",
                              "size": "0"
                            },
                            "validator_candidates": {
                              "id": "0xfb6aa37c2690e2497b209f9431b9624b138c9a88527e93b19487171d0b9f8fb7",
                              "size": "0"
                            },
                            "at_risk_validators": {
                              "contents": []
                            },
                            "extra_fields": {
                              "id": "0x4ffc5f36d43a7412400a46ffb666e23512933843dbaaa616e67285ddf28f60cd",
                              "size": "0"
                            }
                          },
                          "storage_fund": {
                            "total_object_storage_rebates": {
                              "value": "0"
                            },
                            "non_refundable_balance": {
                              "value": "0"
                            }
                          },
                          "parameters": {
                            "epoch_duration_ms": "86400000",
                            "stake_subsidy_start_epoch": "0",
                            "max_validator_count": "150",
                            "min_validator_joining_stake": "30000000000000000",
                            "validator_low_stake_threshold": "20000000000000000",
                            "validator_very_low_stake_threshold": "15000000000000000",
                            "validator_low_stake_grace_period": "7",
                            "extra_fields": {
                              "id": "0xf79643cc4a576afc24ba97cda28776b398634f4c2bac2dc68eeedbf891e4c35f",
                              "size": "0"
                            }
                          },
                          "reference_gas_price": "1000",
                          "validator_report_records": {
                            "contents": []
                          },
                          "stake_subsidy": {
                            "balance": {
                              "value": "9949700000000000000"
                            },
                            "distribution_counter": "0",
                            "current_distribution_amount": "1000000000000000",
                            "stake_subsidy_period_length": "10",
                            "stake_subsidy_decrease_rate": 1000,
                            "extra_fields": {
                              "id": "0xe050c7da3f1fa34b5167e2674dcebd91b46fc6e13c3a66337d24186215aaf795",
                              "size": "0"
                            }
                          },
                          "safe_mode": false,
                          "safe_mode_storage_rewards": {
                            "value": "0"
                          },
                          "safe_mode_computation_rewards": {
                            "value": "0"
                          },
                          "safe_mode_storage_rebates": "0",
                          "safe_mode_non_refundable_storage_fee": "0",
                          "epoch_start_timestamp_ms": "0",
                          "extra_fields": {
                            "id": "0x9adf9fe255f027cd30fe6d82525aa196d2156facbb874c173b0c495422b5bfde",
                            "size": "0"
                          }
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x723fe30ff0842231384bf5bb67ef473afb198ce09851280e206c9dd004d2a665",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x723fe30ff0842231384bf5bb67ef473afb198ce09851280e206c9dd004d2a665",
                        "decimals": 9,
                        "name": "Sui",
                        "symbol": "SUI",
                        "description": "",
                        "icon_url": null
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x8b7d88aaedbd6596fa6be7f1e620d8566844c63c05b0d7dce743b503b782cfe6",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                      },
                      "json": {
                        "id": "0x8b7d88aaedbd6596fa6be7f1e620d8566844c63c05b0d7dce743b503b782cfe6",
                        "name": "0",
                        "value": {
                          "sui_amount": "0",
                          "pool_token_amount": "0"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xa6771f65bfae8727866c2fd95342cd7c2b4ae78c81c90f441640a650ac56cbd3",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                      },
                      "json": {
                        "id": "0xa6771f65bfae8727866c2fd95342cd7c2b4ae78c81c90f441640a650ac56cbd3",
                        "name": "1",
                        "value": {
                          "version": "1",
                          "epoch": "0",
                          "randomness_round": "0",
                          "random_bytes": []
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xbac3a4d946cc4e5680246546d5675555ba28c0da72e54a53ca1098397806a288",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xbac3a4d946cc4e5680246546d5675555ba28c0da72e54a53ca1098397806a288",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorStateInner>"
                      },
                      "json": {
                        "id": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                        "name": "1",
                        "value": {
                          "version": "1",
                          "active_jwks": []
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xeeae7a8a0b89dbde6390dc4ea0e0913e5ef6cb30f4716f3cbd1c79c8dc20e773",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                      },
                      "json": {
                        "id": "0xeeae7a8a0b89dbde6390dc4ea0e0913e5ef6cb30f4716f3cbd1c79c8dc20e773",
                        "name": {
                          "bytes": "0xa85444a8e6d33aee28cc4348423dc68ee2d180e50f6a057640534cae3ab52247"
                        },
                        "value": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": [],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                },
                "amount": "30000000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              },
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "300000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "digest": "366oAKPwjwDSDreXUydf1a21GJLW7PMqtZmEDacfUCHT"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "digest": "3cQpjtPUUFeTiExxcvUbWriji9oLb4AAH5caQKKMrtdP"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "digest": "Hkb5ErdK6jav26Q4U4Qud64u6eX6DdkGQaHCpXqLpEZ2"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "GScL5NnHTsNwoM4yeojX8hottmkH3wC1Aky5hdUaxJ1"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "ATB1gWcLbXeZdXYUzsodGmskccWuGQHpFZyteurfmbqj"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "digest": "5raHYzuSYcqAT3EjRfbcqkermDYqhWRcLaBXXktDP44d"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "digest": "5uGqShhQgpgHd7Cxm2TUxXG1woiDiDa691aMFa9PbDw6"
                }
              },
              {
                "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "digest": "8Q1gnmMjQwq73BFXquQCBKcxouTxL6xFV7vKCEzassDW"
                }
              },
              {
                "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "digest": "Cgky3UA3D6bD2JAzed3oNZLtHUQvPdrFh7npcD6C2PL2"
                }
              },
              {
                "address": "0x367c7571f419221de15a50ed99a1b7b24bdb520a2bfce9792e85a3acda0e94e8",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x367c7571f419221de15a50ed99a1b7b24bdb520a2bfce9792e85a3acda0e94e8",
                  "digest": "BwnrKKt8kACXLXtXCvRWfN9X48sqR7zTHvPwEcckMUAc"
                }
              },
              {
                "address": "0x3d81b8cd6c41269dc5fbe0191492d5512af7921d3323aeb42cdc74566bd4fd5f",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x3d81b8cd6c41269dc5fbe0191492d5512af7921d3323aeb42cdc74566bd4fd5f",
                  "digest": "6CFDAZVKm3QNezRFqgYXoVQPVBroYsgTPZ6u9VMN5tYX"
                }
              },
              {
                "address": "0x4852e90be0c9247073025fc4f3ec785de21642af9be7dc0089e6a917441f9cd0",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x4852e90be0c9247073025fc4f3ec785de21642af9be7dc0089e6a917441f9cd0",
                  "digest": "5ENmNNVqw7pRUKqpwXDdQk5WcJC7VbfMWpNSECBxpgi5"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "digest": "Gks3uANCWoFNhfwFArkam19jizBsmoodQCoh6AhHKQZM"
                }
              },
              {
                "address": "0x723fe30ff0842231384bf5bb67ef473afb198ce09851280e206c9dd004d2a665",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x723fe30ff0842231384bf5bb67ef473afb198ce09851280e206c9dd004d2a665",
                  "digest": "J8MhUszbXk7oLLdD5C6BeqfEy42bALWxtw28P1jvtXZY"
                }
              },
              {
                "address": "0x8b7d88aaedbd6596fa6be7f1e620d8566844c63c05b0d7dce743b503b782cfe6",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x8b7d88aaedbd6596fa6be7f1e620d8566844c63c05b0d7dce743b503b782cfe6",
                  "digest": "96atXLTV9J876cQFsEN31tihMcwtBNX8ZSuNw3S9mRsh"
                }
              },
              {
                "address": "0xa6771f65bfae8727866c2fd95342cd7c2b4ae78c81c90f441640a650ac56cbd3",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xa6771f65bfae8727866c2fd95342cd7c2b4ae78c81c90f441640a650ac56cbd3",
                  "digest": "23yK66kyTTZrL6PrBhUWnE9YDxDLhKaeWA4nNPog9DPQ"
                }
              },
              {
                "address": "0xbac3a4d946cc4e5680246546d5675555ba28c0da72e54a53ca1098397806a288",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xbac3a4d946cc4e5680246546d5675555ba28c0da72e54a53ca1098397806a288",
                  "digest": "4MyxysfQ1ZGhZ1eoSGgFf8kk62LdR5ENGC3sfa8Sxjd9"
                }
              },
              {
                "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "digest": "BR8jm28YwvAD9WMfepbqPGG9T6CVMcBzKuLVPirGy5cE"
                }
              },
              {
                "address": "0xeeae7a8a0b89dbde6390dc4ea0e0913e5ef6cb30f4716f3cbd1c79c8dc20e773",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xeeae7a8a0b89dbde6390dc4ea0e0913e5ef6cb30f4716f3cbd1c79c8dc20e773",
                  "digest": "ChJMAjvMKJHzQHSApr2dYFofXoDidCu9BUezKKqtFz4t"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "7LapPXWc3T9z1TvVgUtxd8TPu334uZNes4bzzDjroRgL"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3 'create-checkpoint'. lines 94-94:
Checkpoint created: 1

task 4 'run-graphql'. lines 96-165:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "7LapPXWc3T9z1TvVgUtxd8TPu334uZNes4bzzDjroRgL"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "28w3Mp2x4vt94bq4TejrbLcfMsMaevDyPz6h98sgcnw4"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6 'advance-epoch'. lines 169-169:
Epoch advanced: 0

task 7 'run-graphql'. lines 171-249:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "ChangeEpochTransaction",
                  "epoch": {
                    "epochId": 1
                  },
                  "protocolVersion": 32,
                  "storageCharge": "0",
                  "computationCharge": "0",
                  "storageRebate": "0",
                  "nonRefundableStorageFee": "0",
                  "startTimestamp": "1970-01-01T00:01:25Z"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "7LapPXWc3T9z1TvVgUtxd8TPu334uZNes4bzzDjroRgL"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "J1C81xskJaop96EsuSZXSxgvodwmMnD9tdDfocXxzrFg"
                }
              },
              {
                "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "digest": "CY9cK5zmeBDVWTy28Psw1XR3ekusuoFSM2iirnztCkrT"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": false,
                "idDeleted": true,
                "outputState": null
              },
              {
                "address": "0xfc552d08a5f641e7a035264a4f26b36b8b0074a18f644ad50486edce80e0616b",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xfc552d08a5f641e7a035264a4f26b36b8b0074a18f644ad50486edce80e0616b",
                  "digest": "BvsY7fHk4hyrJZ3QvmtdNPq81p3Wen5kc5n173MmhBwc"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
