processed 8 tasks

task 1 'run-graphql'. lines 8-90:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "9v9Vk6U47uHF2sLU5Eirqho9izLutgvZSJP4SwyABGRm",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objectConnection": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "ascii"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bit_vector"
                        },
                        {
                          "name": "debug"
                        },
                        {
                          "name": "fixed_point32"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "option"
                        },
                        {
                          "name": "string"
                        },
                        {
                          "name": "type_name"
                        },
                        {
                          "name": "vector"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "authenticator_state"
                        },
                        {
                          "name": "bag"
                        },
                        {
                          "name": "balance"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bls12381"
                        },
                        {
                          "name": "borrow"
                        },
                        {
                          "name": "clock"
                        },
                        {
                          "name": "coin"
                        },
                        {
                          "name": "display"
                        },
                        {
                          "name": "dynamic_field"
                        },
                        {
                          "name": "dynamic_object_field"
                        },
                        {
                          "name": "ecdsa_k1"
                        },
                        {
                          "name": "ecdsa_r1"
                        },
                        {
                          "name": "ecvrf"
                        },
                        {
                          "name": "ed25519"
                        },
                        {
                          "name": "event"
                        },
                        {
                          "name": "groth16"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "hex"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "genesis"
                        },
                        {
                          "name": "stake_subsidy"
                        },
                        {
                          "name": "staking_pool"
                        },
                        {
                          "name": "storage_fund"
                        },
                        {
                          "name": "sui_system"
                        },
                        {
                          "name": "sui_system_state_inner"
                        },
                        {
                          "name": "validator"
                        },
                        {
                          "name": "validator_cap"
                        },
                        {
                          "name": "validator_set"
                        },
                        {
                          "name": "validator_wrapper"
                        },
                        {
                          "name": "voting_power"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                        "timestamp_ms": "0"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                        "inner": {
                          "id": "0x45b970e851e1598e14348d1b312283237c8f585e114d29d298aff8514e171173",
                          "version": "1"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "bridge"
                        },
                        {
                          "name": "btc"
                        },
                        {
                          "name": "chain_ids"
                        },
                        {
                          "name": "committee"
                        },
                        {
                          "name": "eth"
                        },
                        {
                          "name": "message"
                        },
                        {
                          "name": "message_types"
                        },
                        {
                          "name": "treasury"
                        },
                        {
                          "name": "usdc"
                        },
                        {
                          "name": "usdt"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "clob"
                        },
                        {
                          "name": "clob_v2"
                        },
                        {
                          "name": "critbit"
                        },
                        {
                          "name": "custodian"
                        },
                        {
                          "name": "custodian_v2"
                        },
                        {
                          "name": "math"
                        },
                        {
                          "name": "order_query"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x144a878f9c2bcde5c6f022e1b1390b9bec461a1b9800d8fc6ab1c86999fee581",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                      },
                      "json": {
                        "id": "0x144a878f9c2bcde5c6f022e1b1390b9bec461a1b9800d8fc6ab1c86999fee581",
                        "name": "1",
                        "value": {
                          "version": "1",
                          "epoch": "0",
                          "randomness_round": "0",
                          "random_bytes": []
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x2d8375bcd43dbbd027b142d7e11b3c301ae844a19cd1296626fa3d9673f10db8",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x2d8375bcd43dbbd027b142d7e11b3c301ae844a19cd1296626fa3d9673f10db8",
                        "balance": {
                          "value": "30000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x33662a1492158a781efa79607468c90b0e85fe9846fa8240f53219fdd4f7d198",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                      },
                      "json": {
                        "id": "0x33662a1492158a781efa79607468c90b0e85fe9846fa8240f53219fdd4f7d198",
                        "pool_id": {
                          "bytes": "0xe56627aeb430b4623a470bd3125cd425dd797db4f9f606a27d878f1a145ffd3d"
                        },
                        "stake_activation_epoch": "0",
                        "principal": {
                          "value": "20000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x619fde8c81e9b206103a3451c1977433d4f8e33dd2dec17610eae2fd8b16a661",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                      },
                      "json": {
                        "id": "0x619fde8c81e9b206103a3451c1977433d4f8e33dd2dec17610eae2fd8b16a661",
                        "authorizer_validator_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SuiSystemStateInner>"
                      },
                      "json": {
                        "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                        "name": "1",
                        "value": {
                          "epoch": "0",
                          "protocol_version": "32",
                          "system_state_version": "1",
                          "validators": {
                            "total_stake": "20000000000000000",
                            "active_validators": [
                              {
                                "metadata": {
                                  "sui_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244",
                                  "protocol_pubkey_bytes": [
                                    181,
                                    204,
                                    219,
                                    247,
                                    152,
                                    28,
                                    246,
                                    166,
                                    166,
                                    55,
                                    97,
                                    206,
                                    205,
                                    200,
                                    164,
                                    209,
                                    239,
                                    197,
                                    175,
                                    237,
                                    254,
                                    42,
                                    204,
                                    57,
                                    23,
                                    77,
                                    4,
                                    13,
                                    248,
                                    229,
                                    243,
                                    165,
                                    113,
                                    150,
                                    21,
                                    63,
                                    67,
                                    83,
                                    57,
                                    18,
                                    166,
                                    137,
                                    44,
                                    248,
                                    183,
                                    244,
                                    122,
                                    36,
                                    4,
                                    77,
                                    194,
                                    217,
                                    26,
                                    5,
                                    133,
                                    238,
                                    76,
                                    132,
                                    112,
                                    77,
                                    62,
                                    149,
                                    117,
                                    58,
                                    29,
                                    178,
                                    172,
                                    249,
                                    17,
                                    179,
                                    207,
                                    213,
                                    199,
                                    243,
                                    162,
                                    152,
                                    239,
                                    166,
                                    169,
                                    17,
                                    254,
                                    52,
                                    86,
                                    24,
                                    220,
                                    6,
                                    57,
                                    176,
                                    195,
                                    246,
                                    167,
                                    168,
                                    199,
                                    37,
                                    41,
                                    240
                                  ],
                                  "network_pubkey_bytes": [
                                    222,
                                    193,
                                    56,
                                    253,
                                    223,
                                    140,
                                    108,
                                    228,
                                    161,
                                    246,
                                    151,
                                    172,
                                    42,
                                    190,
                                    219,
                                    243,
                                    212,
                                    210,
                                    59,
                                    152,
                                    5,
                                    6,
                                    236,
                                    134,
                                    82,
                                    53,
                                    90,
                                    224,
                                    105,
                                    93,
                                    152,
                                    85
                                  ],
                                  "worker_pubkey_bytes": [
                                    172,
                                    116,
                                    152,
                                    220,
                                    228,
                                    127,
                                    173,
                                    148,
                                    84,
                                    44,
                                    112,
                                    162,
                                    74,
                                    125,
                                    50,
                                    95,
                                    124,
                                    147,
                                    55,
                                    36,
                                    241,
                                    143,
                                    223,
                                    60,
                                    129,
                                    224,
                                    221,
                                    102,
                                    15,
                                    35,
                                    217,
                                    101
                                  ],
                                  "proof_of_possession": [
                                    128,
                                    107,
                                    74,
                                    121,
                                    76,
                                    94,
                                    1,
                                    108,
                                    22,
                                    203,
                                    69,
                                    136,
                                    24,
                                    193,
                                    194,
                                    47,
                                    140,
                                    0,
                                    140,
                                    222,
                                    97,
                                    14,
                                    177,
                                    180,
                                    60,
                                    215,
                                    201,
                                    205,
                                    116,
                                    217,
                                    249,
                                    252,
                                    64,
                                    249,
                                    177,
                                    121,
                                    185,
                                    95,
                                    201,
                                    175,
                                    255,
                                    44,
                                    236,
                                    83,
                                    92,
                                    26,
                                    136,
                                    38
                                  ],
                                  "name": "validator-0",
                                  "description": "",
                                  "image_url": {
                                    "url": ""
                                  },
                                  "project_url": {
                                    "url": ""
                                  },
                                  "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                  "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                  "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                  "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                  "next_epoch_protocol_pubkey_bytes": null,
                                  "next_epoch_proof_of_possession": null,
                                  "next_epoch_network_pubkey_bytes": null,
                                  "next_epoch_worker_pubkey_bytes": null,
                                  "next_epoch_net_address": null,
                                  "next_epoch_p2p_address": null,
                                  "next_epoch_primary_address": null,
                                  "next_epoch_worker_address": null,
                                  "extra_fields": {
                                    "id": "0x944401d2f4b8f11ae70801abfdeb6ee2c199ea273267a1a8b59486da13723570",
                                    "size": "0"
                                  }
                                },
                                "voting_power": "10000",
                                "operation_cap_id": {
                                  "bytes": "0x619fde8c81e9b206103a3451c1977433d4f8e33dd2dec17610eae2fd8b16a661"
                                },
                                "gas_price": "1000",
                                "staking_pool": {
                                  "id": "0xe56627aeb430b4623a470bd3125cd425dd797db4f9f606a27d878f1a145ffd3d",
                                  "activation_epoch": "0",
                                  "deactivation_epoch": null,
                                  "sui_balance": "20000000000000000",
                                  "rewards_pool": {
                                    "value": "0"
                                  },
                                  "pool_token_balance": "20000000000000000",
                                  "exchange_rates": {
                                    "id": "0xfe8dfa0b26a9893c303521890c6af1ebfcbb72b3b6633149b8d17981b1f6050e",
                                    "size": "1"
                                  },
                                  "pending_stake": "0",
                                  "pending_total_sui_withdraw": "0",
                                  "pending_pool_token_withdraw": "0",
                                  "extra_fields": {
                                    "id": "0xf5fdec514af5eda33020d99c6e6a3313b74583228f5a9a7b707c1a9562faf67d",
                                    "size": "0"
                                  }
                                },
                                "commission_rate": "200",
                                "next_epoch_stake": "20000000000000000",
                                "next_epoch_gas_price": "1000",
                                "next_epoch_commission_rate": "200",
                                "extra_fields": {
                                  "id": "0x3cc3742e15cfa804e4246441cc48ec0eeaa8ad45d5588c50c0c1cec11324cdb4",
                                  "size": "0"
                                }
                              }
                            ],
                            "pending_active_validators": {
                              "contents": {
                                "id": "0x21631369957f6424301304141095425fdb2bf93785f96c5646c57fc10ca7e2bf",
                                "size": "0"
                              }
                            },
                            "pending_removals": [],
                            "staking_pool_mappings": {
                              "id": "0x35a45696a4c5d97eed7a5ecd72262b8245e2b88f6be13c6eb919c65e6a184515",
                              "size": "1"
                            },
                            "inactive_validators": {
                              "id": "0x33ad354d99b9f2da2aacbe648a8d11dc1c12ede2933a679341b0204d792e8d29",
                              "size": "0"
                            },
                            "validator_candidates": {
                              "id": "0xa0ddfc51705fa6b2ccca94dd13a4879029a88f570ac197a0a21149a97d3620ae",
                              "size": "0"
                            },
                            "at_risk_validators": {
                              "contents": []
                            },
                            "extra_fields": {
                              "id": "0xb6576f56b9b3c427b3e428195c4bfdb7163d1a612b8747bb58c166ab5aa8ea63",
                              "size": "0"
                            }
                          },
                          "storage_fund": {
                            "total_object_storage_rebates": {
                              "value": "0"
                            },
                            "non_refundable_balance": {
                              "value": "0"
                            }
                          },
                          "parameters": {
                            "epoch_duration_ms": "86400000",
                            "stake_subsidy_start_epoch": "0",
                            "max_validator_count": "150",
                            "min_validator_joining_stake": "30000000000000000",
                            "validator_low_stake_threshold": "20000000000000000",
                            "validator_very_low_stake_threshold": "15000000000000000",
                            "validator_low_stake_grace_period": "7",
                            "extra_fields": {
                              "id": "0x73bdaffa60e027cf477a5e10917de57d1eb88881eacf923e751f1dd650714cc5",
                              "size": "0"
                            }
                          },
                          "reference_gas_price": "1000",
                          "validator_report_records": {
                            "contents": []
                          },
                          "stake_subsidy": {
                            "balance": {
                              "value": "9949700000000000000"
                            },
                            "distribution_counter": "0",
                            "current_distribution_amount": "1000000000000000",
                            "stake_subsidy_period_length": "10",
                            "stake_subsidy_decrease_rate": 1000,
                            "extra_fields": {
                              "id": "0x799c1484d24ca2487e46e979a32442ae2a48fbd0cf9e6e12c3bc7303df47a5cb",
                              "size": "0"
                            }
                          },
                          "safe_mode": false,
                          "safe_mode_storage_rewards": {
                            "value": "0"
                          },
                          "safe_mode_computation_rewards": {
                            "value": "0"
                          },
                          "safe_mode_storage_rebates": "0",
                          "safe_mode_non_refundable_storage_fee": "0",
                          "epoch_start_timestamp_ms": "0",
                          "extra_fields": {
                            "id": "0xaab1aebf86d7a367e030488e0afb5cb20ef622ee82916dfcdd4b6bedf682a5a1",
                            "size": "0"
                          }
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x795b84f72bd8ff645aede7ba27720a0d84cff39dfc5373b0ffb33414dcf419d9",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x795b84f72bd8ff645aede7ba27720a0d84cff39dfc5373b0ffb33414dcf419d9",
                        "decimals": 9,
                        "name": "Sui",
                        "symbol": "SUI",
                        "description": "",
                        "icon_url": null
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x9dcc53e67a13eccf12ce5ee021e4a0b35acad1bd299b971bfddfb43e1f5d0af1",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                      },
                      "json": {
                        "id": "0x9dcc53e67a13eccf12ce5ee021e4a0b35acad1bd299b971bfddfb43e1f5d0af1",
                        "name": {
                          "bytes": "0xe56627aeb430b4623a470bd3125cd425dd797db4f9f606a27d878f1a145ffd3d"
                        },
                        "value": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorStateInner>"
                      },
                      "json": {
                        "id": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                        "name": "1",
                        "value": {
                          "version": "1",
                          "active_jwks": []
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xf638b1aafe3f8a9a4423b7fb050db82e7de5d47eeae5dbe732abcd3b3f16756a",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                      },
                      "json": {
                        "id": "0xf638b1aafe3f8a9a4423b7fb050db82e7de5d47eeae5dbe732abcd3b3f16756a",
                        "name": "0",
                        "value": {
                          "sui_amount": "0",
                          "pool_token_amount": "0"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xff3e53faee087188f3cce2db7ebf811f0cb6d14239cfcf6815a8546ae16719ef",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xff3e53faee087188f3cce2db7ebf811f0cb6d14239cfcf6815a8546ae16719ef",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": [],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                },
                "amount": "30000000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              },
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "300000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "digest": "6bqtLxtd3uchhLcEEpNSLh9enKh5bnvqApQ4WrYHMgCA"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "digest": "FE5M9vUv2VVX4vwQ7MNdpcJ3iqffCTZFSXD1hhpzCZTb"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "digest": "86j1JPAKSVh8QM55sxvEA6KxaV2AwRcMGZckFLYA4MPo"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "FWW8z7Loi3h6TUnseDP55cgZwbBTUrFuvJQVVETZ9rHa"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "BFuJbQQDQzgbFGqgcQAYqPc4oQ8GNDbtxwes6pCBogdT"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "digest": "44cZm7pZFMuqoNtdJEtnFRPJ4bEfJhWqg1Wtxnf9DWez"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "digest": "4Cmri9TVMZBuBUcGJ6BAS3mBVy3UmjY8MYYDXN3C8ncK"
                }
              },
              {
                "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "digest": "BRPMFQZZSvGHgYKwtZwU9rEFoMApz1We4mWF7S8UDSNW"
                }
              },
              {
                "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "digest": "GGhtekhfY12mSvLNZBNSZbRGqdGYh4wDJUx1X94gBCA"
                }
              },
              {
                "address": "0x144a878f9c2bcde5c6f022e1b1390b9bec461a1b9800d8fc6ab1c86999fee581",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x144a878f9c2bcde5c6f022e1b1390b9bec461a1b9800d8fc6ab1c86999fee581",
                  "digest": "9QjaeS7qQLa2syd28RGxzAipu6Bvt7KNG97kUpe1ma4L"
                }
              },
              {
                "address": "0x2d8375bcd43dbbd027b142d7e11b3c301ae844a19cd1296626fa3d9673f10db8",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x2d8375bcd43dbbd027b142d7e11b3c301ae844a19cd1296626fa3d9673f10db8",
                  "digest": "9bs63PmaK5Xqg9fpJSAfzYV6WU7KqLPCwpCo8qeNvaa9"
                }
              },
              {
                "address": "0x33662a1492158a781efa79607468c90b0e85fe9846fa8240f53219fdd4f7d198",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x33662a1492158a781efa79607468c90b0e85fe9846fa8240f53219fdd4f7d198",
                  "digest": "Eh2MR4AyM11uv26R9ecB629RN18zgLigBLEJbzcgFZ1P"
                }
              },
              {
                "address": "0x619fde8c81e9b206103a3451c1977433d4f8e33dd2dec17610eae2fd8b16a661",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x619fde8c81e9b206103a3451c1977433d4f8e33dd2dec17610eae2fd8b16a661",
                  "digest": "AyUerPDB7voEL2yCkPsVrhLeaFCvbE2zrGXAJoTNsrX1"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "digest": "2zwnue5nsyT4eVgVbWvzgpDu25HJVJtAv3C7vNCoNCL6"
                }
              },
              {
                "address": "0x795b84f72bd8ff645aede7ba27720a0d84cff39dfc5373b0ffb33414dcf419d9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x795b84f72bd8ff645aede7ba27720a0d84cff39dfc5373b0ffb33414dcf419d9",
                  "digest": "6LQQDyT6cbyPan6DnAuPCokc6oj3phxGLT2ejts7sUiP"
                }
              },
              {
                "address": "0x9dcc53e67a13eccf12ce5ee021e4a0b35acad1bd299b971bfddfb43e1f5d0af1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x9dcc53e67a13eccf12ce5ee021e4a0b35acad1bd299b971bfddfb43e1f5d0af1",
                  "digest": "CyZXQsEWfMQzZwju3ZyY3ofYkTt3qhGH66GkgSU9D9ao"
                }
              },
              {
                "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "digest": "33hYGnsveZocVP2uiRGdJJ6mZgLhRS2qSTbmHLxSLQao"
                }
              },
              {
                "address": "0xf638b1aafe3f8a9a4423b7fb050db82e7de5d47eeae5dbe732abcd3b3f16756a",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xf638b1aafe3f8a9a4423b7fb050db82e7de5d47eeae5dbe732abcd3b3f16756a",
                  "digest": "9KCmVS2LV8rv83yEJhwaenZrtizfVmP18r93D3sbifiW"
                }
              },
              {
                "address": "0xff3e53faee087188f3cce2db7ebf811f0cb6d14239cfcf6815a8546ae16719ef",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xff3e53faee087188f3cce2db7ebf811f0cb6d14239cfcf6815a8546ae16719ef",
                  "digest": "BEjbrvXv1Rk4XwiApGDVismPxFr7EN6WpXUuhFjNSmvx"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "9v9Vk6U47uHF2sLU5Eirqho9izLutgvZSJP4SwyABGRm"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3 'create-checkpoint'. lines 94-94:
Checkpoint created: 1

task 4 'run-graphql'. lines 96-165:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "9v9Vk6U47uHF2sLU5Eirqho9izLutgvZSJP4SwyABGRm"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "28w3Mp2x4vt94bq4TejrbLcfMsMaevDyPz6h98sgcnw4"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6 'advance-epoch'. lines 169-169:
Epoch advanced: 0

task 7 'run-graphql'. lines 171-249:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "ChangeEpochTransaction",
                  "epoch": {
                    "epochId": 1
                  },
                  "protocolVersion": 32,
                  "storageCharge": "0",
                  "computationCharge": "0",
                  "storageRebate": "0",
                  "nonRefundableStorageFee": "0",
                  "startTimestamp": "1970-01-01T00:01:25Z"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "9v9Vk6U47uHF2sLU5Eirqho9izLutgvZSJP4SwyABGRm"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "J1C81xskJaop96EsuSZXSxgvodwmMnD9tdDfocXxzrFg"
                }
              },
              {
                "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "digest": "6yryWdvZUWMSejfxB3SFKzhjJpBrUCjxQWK2Y9ciZQBE"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": false,
                "idDeleted": true,
                "outputState": null
              },
              {
                "address": "0xf7c083826439e8178311d7c486785d3800300de163abc56d55e9ee48fbb6007d",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xf7c083826439e8178311d7c486785d3800300de163abc56d55e9ee48fbb6007d",
                  "digest": "DjryeGbSPLgu4ft9YLCDnvvPqvxgEth1N9k2dzmFbcF3"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
