processed 8 tasks

task 1 'run-graphql'. lines 8-90:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "4jRq53dFutF8VoKd8fzNWXLNqRLh9AYuLKDA62tBviAW",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objectConnection": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "ascii"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bit_vector"
                        },
                        {
                          "name": "debug"
                        },
                        {
                          "name": "fixed_point32"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "option"
                        },
                        {
                          "name": "string"
                        },
                        {
                          "name": "type_name"
                        },
                        {
                          "name": "vector"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "authenticator_state"
                        },
                        {
                          "name": "bag"
                        },
                        {
                          "name": "balance"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bls12381"
                        },
                        {
                          "name": "borrow"
                        },
                        {
                          "name": "clock"
                        },
                        {
                          "name": "coin"
                        },
                        {
                          "name": "display"
                        },
                        {
                          "name": "dynamic_field"
                        },
                        {
                          "name": "dynamic_object_field"
                        },
                        {
                          "name": "ecdsa_k1"
                        },
                        {
                          "name": "ecdsa_r1"
                        },
                        {
                          "name": "ecvrf"
                        },
                        {
                          "name": "ed25519"
                        },
                        {
                          "name": "event"
                        },
                        {
                          "name": "groth16"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "hex"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "genesis"
                        },
                        {
                          "name": "stake_subsidy"
                        },
                        {
                          "name": "staking_pool"
                        },
                        {
                          "name": "storage_fund"
                        },
                        {
                          "name": "sui_system"
                        },
                        {
                          "name": "sui_system_state_inner"
                        },
                        {
                          "name": "validator"
                        },
                        {
                          "name": "validator_cap"
                        },
                        {
                          "name": "validator_set"
                        },
                        {
                          "name": "validator_wrapper"
                        },
                        {
                          "name": "voting_power"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                        "timestamp_ms": "0"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                        "inner": {
                          "id": "0xfa78b169b0360a860aa155682f6592276e9b642b813bc4656dcb54847ab13b69",
                          "version": "1"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "bridge"
                        },
                        {
                          "name": "btc"
                        },
                        {
                          "name": "chain_ids"
                        },
                        {
                          "name": "committee"
                        },
                        {
                          "name": "eth"
                        },
                        {
                          "name": "message"
                        },
                        {
                          "name": "message_types"
                        },
                        {
                          "name": "treasury"
                        },
                        {
                          "name": "usdc"
                        },
                        {
                          "name": "usdt"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "clob"
                        },
                        {
                          "name": "clob_v2"
                        },
                        {
                          "name": "critbit"
                        },
                        {
                          "name": "custodian"
                        },
                        {
                          "name": "custodian_v2"
                        },
                        {
                          "name": "math"
                        },
                        {
                          "name": "order_query"
                        }
                      ]
                    }
                  }
                },
                {
                  "address": "0x2a2a1e87a3030499d7ddc639db07618550cacbf169d3790010bae0f7535a322e",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                      },
                      "json": {
                        "id": "0x2a2a1e87a3030499d7ddc639db07618550cacbf169d3790010bae0f7535a322e",
                        "name": "0",
                        "value": {
                          "sui_amount": "0",
                          "pool_token_amount": "0"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x5721b03f5a97f176419780f1f8b101f2b2982973e361c16c9a336e73baf0159e",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                      },
                      "json": {
                        "id": "0x5721b03f5a97f176419780f1f8b101f2b2982973e361c16c9a336e73baf0159e",
                        "name": {
                          "bytes": "0x0ed8ff122726705cfb1eb365a1586c7dea5aba28107df09e8a808304e0f5e401"
                        },
                        "value": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SuiSystemStateInner>"
                      },
                      "json": {
                        "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                        "name": "1",
                        "value": {
                          "epoch": "0",
                          "protocol_version": "32",
                          "system_state_version": "1",
                          "validators": {
                            "total_stake": "20000000000000000",
                            "active_validators": [
                              {
                                "metadata": {
                                  "sui_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244",
                                  "protocol_pubkey_bytes": [
                                    181,
                                    204,
                                    219,
                                    247,
                                    152,
                                    28,
                                    246,
                                    166,
                                    166,
                                    55,
                                    97,
                                    206,
                                    205,
                                    200,
                                    164,
                                    209,
                                    239,
                                    197,
                                    175,
                                    237,
                                    254,
                                    42,
                                    204,
                                    57,
                                    23,
                                    77,
                                    4,
                                    13,
                                    248,
                                    229,
                                    243,
                                    165,
                                    113,
                                    150,
                                    21,
                                    63,
                                    67,
                                    83,
                                    57,
                                    18,
                                    166,
                                    137,
                                    44,
                                    248,
                                    183,
                                    244,
                                    122,
                                    36,
                                    4,
                                    77,
                                    194,
                                    217,
                                    26,
                                    5,
                                    133,
                                    238,
                                    76,
                                    132,
                                    112,
                                    77,
                                    62,
                                    149,
                                    117,
                                    58,
                                    29,
                                    178,
                                    172,
                                    249,
                                    17,
                                    179,
                                    207,
                                    213,
                                    199,
                                    243,
                                    162,
                                    152,
                                    239,
                                    166,
                                    169,
                                    17,
                                    254,
                                    52,
                                    86,
                                    24,
                                    220,
                                    6,
                                    57,
                                    176,
                                    195,
                                    246,
                                    167,
                                    168,
                                    199,
                                    37,
                                    41,
                                    240
                                  ],
                                  "network_pubkey_bytes": [
                                    222,
                                    193,
                                    56,
                                    253,
                                    223,
                                    140,
                                    108,
                                    228,
                                    161,
                                    246,
                                    151,
                                    172,
                                    42,
                                    190,
                                    219,
                                    243,
                                    212,
                                    210,
                                    59,
                                    152,
                                    5,
                                    6,
                                    236,
                                    134,
                                    82,
                                    53,
                                    90,
                                    224,
                                    105,
                                    93,
                                    152,
                                    85
                                  ],
                                  "worker_pubkey_bytes": [
                                    172,
                                    116,
                                    152,
                                    220,
                                    228,
                                    127,
                                    173,
                                    148,
                                    84,
                                    44,
                                    112,
                                    162,
                                    74,
                                    125,
                                    50,
                                    95,
                                    124,
                                    147,
                                    55,
                                    36,
                                    241,
                                    143,
                                    223,
                                    60,
                                    129,
                                    224,
                                    221,
                                    102,
                                    15,
                                    35,
                                    217,
                                    101
                                  ],
                                  "proof_of_possession": [
                                    128,
                                    107,
                                    74,
                                    121,
                                    76,
                                    94,
                                    1,
                                    108,
                                    22,
                                    203,
                                    69,
                                    136,
                                    24,
                                    193,
                                    194,
                                    47,
                                    140,
                                    0,
                                    140,
                                    222,
                                    97,
                                    14,
                                    177,
                                    180,
                                    60,
                                    215,
                                    201,
                                    205,
                                    116,
                                    217,
                                    249,
                                    252,
                                    64,
                                    249,
                                    177,
                                    121,
                                    185,
                                    95,
                                    201,
                                    175,
                                    255,
                                    44,
                                    236,
                                    83,
                                    92,
                                    26,
                                    136,
                                    38
                                  ],
                                  "name": "validator-0",
                                  "description": "",
                                  "image_url": {
                                    "url": ""
                                  },
                                  "project_url": {
                                    "url": ""
                                  },
                                  "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                  "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                  "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                  "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                  "next_epoch_protocol_pubkey_bytes": null,
                                  "next_epoch_proof_of_possession": null,
                                  "next_epoch_network_pubkey_bytes": null,
                                  "next_epoch_worker_pubkey_bytes": null,
                                  "next_epoch_net_address": null,
                                  "next_epoch_p2p_address": null,
                                  "next_epoch_primary_address": null,
                                  "next_epoch_worker_address": null,
                                  "extra_fields": {
                                    "id": "0xadb8ba4ef033b2ad38ea521fb7e5af56fa0b49cc49019aca0a2371f0543c6459",
                                    "size": "0"
                                  }
                                },
                                "voting_power": "10000",
                                "operation_cap_id": {
                                  "bytes": "0xc3854d57db3b45dbbab82681f70361974898f65e95d98fd4503c36b82716d9ea"
                                },
                                "gas_price": "1000",
                                "staking_pool": {
                                  "id": "0x0ed8ff122726705cfb1eb365a1586c7dea5aba28107df09e8a808304e0f5e401",
                                  "activation_epoch": "0",
                                  "deactivation_epoch": null,
                                  "sui_balance": "20000000000000000",
                                  "rewards_pool": {
                                    "value": "0"
                                  },
                                  "pool_token_balance": "20000000000000000",
                                  "exchange_rates": {
                                    "id": "0xaedc70f5a37f88129833d4ab2fc6296ee5203ff7ec377f7a5ba8ff2ada9d8460",
                                    "size": "1"
                                  },
                                  "pending_stake": "0",
                                  "pending_total_sui_withdraw": "0",
                                  "pending_pool_token_withdraw": "0",
                                  "extra_fields": {
                                    "id": "0x0c615fd5a4b2361adeae3a39608366492f4d8f6e918c972b04675328545af4bf",
                                    "size": "0"
                                  }
                                },
                                "commission_rate": "200",
                                "next_epoch_stake": "20000000000000000",
                                "next_epoch_gas_price": "1000",
                                "next_epoch_commission_rate": "200",
                                "extra_fields": {
                                  "id": "0x83dee412db7921b10f99ca12fcfabbeba29c4e1c33d77eca13e6c235c8f43fb2",
                                  "size": "0"
                                }
                              }
                            ],
                            "pending_active_validators": {
                              "contents": {
                                "id": "0x29f97adb00fd6f8e43c5772ee58a3bfd14e2e553ee8de9b184d707ff79af7dfa",
                                "size": "0"
                              }
                            },
                            "pending_removals": [],
                            "staking_pool_mappings": {
                              "id": "0xdd41c3d20a2ef5419c0550da4fc36cfcc78b8f4d6db7758f6a43f4304e6972a6",
                              "size": "1"
                            },
                            "inactive_validators": {
                              "id": "0xf4b9224bbb7b118b940a2e4cb7683b32a42c72d56513b0fa541dd419bc22c712",
                              "size": "0"
                            },
                            "validator_candidates": {
                              "id": "0xf38e83c9c97131aa0772605042c2845d9f16d584ea4360b97b177f8a53525950",
                              "size": "0"
                            },
                            "at_risk_validators": {
                              "contents": []
                            },
                            "extra_fields": {
                              "id": "0x06daed19ed9354f2f276917d5b27b583753252fb1b29a4cd10459206c5ee46ac",
                              "size": "0"
                            }
                          },
                          "storage_fund": {
                            "total_object_storage_rebates": {
                              "value": "0"
                            },
                            "non_refundable_balance": {
                              "value": "0"
                            }
                          },
                          "parameters": {
                            "epoch_duration_ms": "86400000",
                            "stake_subsidy_start_epoch": "0",
                            "max_validator_count": "150",
                            "min_validator_joining_stake": "30000000000000000",
                            "validator_low_stake_threshold": "20000000000000000",
                            "validator_very_low_stake_threshold": "15000000000000000",
                            "validator_low_stake_grace_period": "7",
                            "extra_fields": {
                              "id": "0x6491a8bb95c9fdb2a583ef537ca22218597a50f19c46c31c77cf29cd1af1fbad",
                              "size": "0"
                            }
                          },
                          "reference_gas_price": "1000",
                          "validator_report_records": {
                            "contents": []
                          },
                          "stake_subsidy": {
                            "balance": {
                              "value": "9949700000000000000"
                            },
                            "distribution_counter": "0",
                            "current_distribution_amount": "1000000000000000",
                            "stake_subsidy_period_length": "10",
                            "stake_subsidy_decrease_rate": 1000,
                            "extra_fields": {
                              "id": "0xf1315709aa8c790b72217faf0fe648c2bc51937f2e7816d13d273354a1213c81",
                              "size": "0"
                            }
                          },
                          "safe_mode": false,
                          "safe_mode_storage_rewards": {
                            "value": "0"
                          },
                          "safe_mode_computation_rewards": {
                            "value": "0"
                          },
                          "safe_mode_storage_rebates": "0",
                          "safe_mode_non_refundable_storage_fee": "0",
                          "epoch_start_timestamp_ms": "0",
                          "extra_fields": {
                            "id": "0xa08e7c2f7a300af888b4998a870b37d6fe4ce42b77321d3c9223fab190007c39",
                            "size": "0"
                          }
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0x787011347251fb4e2fe2eb9e44b6340aa88ad274d823665b5330e57c84d5e3fd",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x787011347251fb4e2fe2eb9e44b6340aa88ad274d823665b5330e57c84d5e3fd",
                        "decimals": 9,
                        "name": "Sui",
                        "symbol": "SUI",
                        "description": "",
                        "icon_url": null
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xa2243a5cdaf7b8ce0d5bd428ff6329b3d3d34e85e907636a7df43595fd6f42fb",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xa2243a5cdaf7b8ce0d5bd428ff6329b3d3d34e85e907636a7df43595fd6f42fb",
                        "balance": {
                          "value": "30000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xa8038c7de62ac71775b520130f18d89e9d635ce2993863b4bfa635256b181104",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                      },
                      "json": {
                        "id": "0xa8038c7de62ac71775b520130f18d89e9d635ce2993863b4bfa635256b181104",
                        "pool_id": {
                          "bytes": "0x0ed8ff122726705cfb1eb365a1586c7dea5aba28107df09e8a808304e0f5e401"
                        },
                        "stake_activation_epoch": "0",
                        "principal": {
                          "value": "20000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xb243a5e8b8f3e3b0ae87c264141aa6ca949a0069ffcf99d6660ce3dbb8c8af63",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xb243a5e8b8f3e3b0ae87c264141aa6ca949a0069ffcf99d6660ce3dbb8c8af63",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xc3854d57db3b45dbbab82681f70361974898f65e95d98fd4503c36b82716d9ea",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                      },
                      "json": {
                        "id": "0xc3854d57db3b45dbbab82681f70361974898f65e95d98fd4503c36b82716d9ea",
                        "authorizer_validator_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorStateInner>"
                      },
                      "json": {
                        "id": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                        "name": "1",
                        "value": {
                          "version": "1",
                          "active_jwks": []
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "address": "0xf05c6102169d11242fb159602a8da140d8430a663681a31bdf8f4deae372e913",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                      },
                      "json": {
                        "id": "0xf05c6102169d11242fb159602a8da140d8430a663681a31bdf8f4deae372e913",
                        "name": "1",
                        "value": {
                          "version": "1",
                          "epoch": "0",
                          "randomness_round": "0",
                          "random_bytes": []
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": [],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                },
                "amount": "30000000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              },
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "300000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "digest": "52BXP2M1ByMrvxDwSiEw4eY65xziuXtMPCp2bhR13MPM"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "digest": "M3yxk3gRxc8fejLJaPKjMGJCP4SHCHmgVZnCJRa72uz"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "digest": "DaBgGqN52eP8pLnnG9emhYCfjr5T93e4hUcasgzDYUR4"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "2WW5tQyRnZrfrhFQLDp7h963QzYxFzS94W7EV3MzEPd3"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "36cUCnZfo3QajCgLzEVguZJBegrRuRv6BDdbYquP6hL9"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "digest": "6hbcHYnp1j1LqDUJGcdbnXz38HYH3pSgHmEv7tq7d6L9"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "digest": "9qwLtdvHG2HhCVQc3FBUDTtjYeXkka6iVhgzX958F3KF"
                }
              },
              {
                "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "digest": "CoheQwM1AXcAd4zHaXMiiq3G5dF3EhvX6xvdeRfBt3pJ"
                }
              },
              {
                "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "digest": "23x5PQ68tpLG2sokurAQJ7LB4YQXV2KTQ7u8wgZGWkTW"
                }
              },
              {
                "address": "0x2a2a1e87a3030499d7ddc639db07618550cacbf169d3790010bae0f7535a322e",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x2a2a1e87a3030499d7ddc639db07618550cacbf169d3790010bae0f7535a322e",
                  "digest": "84C6Mcx7FFUpdb82t57CKLuWu2QMWxHiwsdsm4QGjtJs"
                }
              },
              {
                "address": "0x5721b03f5a97f176419780f1f8b101f2b2982973e361c16c9a336e73baf0159e",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5721b03f5a97f176419780f1f8b101f2b2982973e361c16c9a336e73baf0159e",
                  "digest": "7gszC2j1qtKPtXxBzYQJ1RfiFwd9cDJ9bdohr4S2tCFT"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "digest": "C7pdD6weQEeR5K3ptDsn6QYzCDwn5Txi3bD7HRyHk4V2"
                }
              },
              {
                "address": "0x787011347251fb4e2fe2eb9e44b6340aa88ad274d823665b5330e57c84d5e3fd",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x787011347251fb4e2fe2eb9e44b6340aa88ad274d823665b5330e57c84d5e3fd",
                  "digest": "BqdPjYHAJD7PS8cwZ7aRrgC7m5fSnwMdTjZVDhVRtWW4"
                }
              },
              {
                "address": "0xa2243a5cdaf7b8ce0d5bd428ff6329b3d3d34e85e907636a7df43595fd6f42fb",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xa2243a5cdaf7b8ce0d5bd428ff6329b3d3d34e85e907636a7df43595fd6f42fb",
                  "digest": "BUgxe9T8RxHr9xhcwN7dvo7X23a5mjiHBxtACjfDj8fK"
                }
              },
              {
                "address": "0xa8038c7de62ac71775b520130f18d89e9d635ce2993863b4bfa635256b181104",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xa8038c7de62ac71775b520130f18d89e9d635ce2993863b4bfa635256b181104",
                  "digest": "DqwwNxJHaWLJPyvxqpnAzJuZp7yX3EfoRH7ZUNGThx1a"
                }
              },
              {
                "address": "0xb243a5e8b8f3e3b0ae87c264141aa6ca949a0069ffcf99d6660ce3dbb8c8af63",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xb243a5e8b8f3e3b0ae87c264141aa6ca949a0069ffcf99d6660ce3dbb8c8af63",
                  "digest": "HhJVkRKxrEGUeaJJBcMPUkVEX4LVHjr9DTYdi5sniPxP"
                }
              },
              {
                "address": "0xc3854d57db3b45dbbab82681f70361974898f65e95d98fd4503c36b82716d9ea",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xc3854d57db3b45dbbab82681f70361974898f65e95d98fd4503c36b82716d9ea",
                  "digest": "kajCJBrJPGegw1oKJGRjwK3NJbKviiZzd5cqrVDK7Aq"
                }
              },
              {
                "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "digest": "4qRFVNkjP17FCvodXQLhNV1zcCSDwjzwRkK3Ebmo7EGq"
                }
              },
              {
                "address": "0xf05c6102169d11242fb159602a8da140d8430a663681a31bdf8f4deae372e913",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xf05c6102169d11242fb159602a8da140d8430a663681a31bdf8f4deae372e913",
                  "digest": "A83iD33zo6g7Y6jiEgmYN6HUqc7XC8f3Nzd2UjXZ4MWf"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "4jRq53dFutF8VoKd8fzNWXLNqRLh9AYuLKDA62tBviAW"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3 'create-checkpoint'. lines 94-94:
Checkpoint created: 1

task 4 'run-graphql'. lines 96-165:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "4jRq53dFutF8VoKd8fzNWXLNqRLh9AYuLKDA62tBviAW"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "28w3Mp2x4vt94bq4TejrbLcfMsMaevDyPz6h98sgcnw4"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6 'advance-epoch'. lines 169-169:
Epoch advanced: 0

task 7 'run-graphql'. lines 171-249:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactionConnection": {
              "nodes": [
                {
                  "__typename": "ChangeEpochTransaction",
                  "epoch": {
                    "epochId": 1
                  },
                  "protocolVersion": 32,
                  "storageCharge": "0",
                  "computationCharge": "0",
                  "storageRebate": "0",
                  "nonRefundableStorageFee": "0",
                  "startTimestamp": "1970-01-01T00:01:25Z"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "4jRq53dFutF8VoKd8fzNWXLNqRLh9AYuLKDA62tBviAW"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "J1C81xskJaop96EsuSZXSxgvodwmMnD9tdDfocXxzrFg"
                }
              },
              {
                "address": "0x3d12f9d4b9dbec64ab2586f7fb28fcdc8337c6c1f0d0ff8d9ff8b187ea3e5f2d",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x3d12f9d4b9dbec64ab2586f7fb28fcdc8337c6c1f0d0ff8d9ff8b187ea3e5f2d",
                  "digest": "GSchDrMTvfbyoV5JZRM1fh4BueDAwszRzZAAQHAjsB3A"
                }
              },
              {
                "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "digest": "4RmtzeT6fL8fGk73wrBGqvLEVREZUb1buF1SnYkVNSLL"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": false,
                "idDeleted": true,
                "outputState": null
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
