processed 26 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-47:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7014800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 49-49:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 51-51:
Checkpoint created: 1

task 4 'run-graphql'. lines 53-66:
Response: {
  "data": {
    "object": {
      "status": "LIVE",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "0"
          }
        }
      }
    }
  }
}

task 5 'run'. lines 68-68:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 6 'create-checkpoint'. lines 70-70:
Checkpoint created: 2

task 7 'run-graphql'. lines 72-85:
Response: {
  "data": {
    "object": {
      "status": "LIVE",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "1"
          }
        }
      }
    }
  }
}

task 8 'run-graphql'. lines 87-101:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "0"
          }
        }
      }
    }
  }
}

task 9 'run'. lines 103-103:
created: object(9,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 10 'create-checkpoint'. lines 105-105:
Checkpoint created: 3

task 11 'run-graphql'. lines 107-120:
Response: {
  "data": {
    "object": null
  }
}

task 12 'run-graphql'. lines 123-137:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "1"
          }
        }
      }
    }
  }
}

task 13 'run-graphql'. lines 139-153:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "0"
          }
        }
      }
    }
  }
}

task 14 'run'. lines 155-155:
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(9,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 15 'create-checkpoint'. lines 157-157:
Checkpoint created: 4

task 16 'run-graphql'. lines 159-172:
Response: {
  "data": {
    "object": {
      "status": "LIVE",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "1"
          }
        }
      }
    }
  }
}

task 17 'run-graphql'. lines 174-188:
Response: {
  "data": {
    "object": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    }
  }
}

task 18 'run-graphql'. lines 190-204:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "1"
          }
        }
      }
    }
  }
}

task 19 'run-graphql'. lines 206-220:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "0"
          }
        }
      }
    }
  }
}

task 20 'run'. lines 222-222:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 21 'create-checkpoint'. lines 224-224:
Checkpoint created: 5

task 22 'run-graphql'. lines 226-239:
Response: {
  "data": {
    "object": null
  }
}

task 23 'run-graphql'. lines 241-255:
Response: {
  "data": {
    "object": {
      "status": "WRAPPED_OR_DELETED",
      "version": 7,
      "asMoveObject": null
    }
  }
}

task 24 'run-graphql'. lines 257-271:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf33ea2d61d60ef63e7aa7570a8a6f053c061ed5b98e4dbff09aa0e9316f7e9ed",
            "value": "1"
          }
        }
      }
    }
  }
}

task 25 'run-graphql'. lines 273-287:
Response: {
  "data": {
    "object": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    }
  }
}
