processed 13 tasks

task 1 'publish'. lines 6-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 25-25:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 27-27:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 29-29:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 31-31:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 33-33:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 8 'run-graphql'. lines 37-47:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x35c9792ee0738f694075f1d6f4840e977f238ac20e64adcc00c542b8883ad32c"
          },
          {
            "cursor": "0x44ec5d1efa78a3901ae380bddc83398bb42661dace5fc9d1097de974aaaee62c"
          },
          {
            "cursor": "0xa40b9acac25c205ead0c0dc425e88ffc7750843481317178e1b9c4bb23d1721b"
          },
          {
            "cursor": "0xc6cc506581a7262a65ba7ff09aba44a66a5276a62f2d387ed46bc40c190735f2"
          },
          {
            "cursor": "0xffbb5412f9f5e7113017aa7256832fb8577f492674026134edf7442089b3b5f3"
          }
        ]
      }
    }
  }
}

task 9 'run-graphql'. lines 49-59:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x35c9792ee0738f694075f1d6f4840e977f238ac20e64adcc00c542b8883ad32c"
          },
          {
            "cursor": "0x44ec5d1efa78a3901ae380bddc83398bb42661dace5fc9d1097de974aaaee62c"
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 61-73:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xffbb5412f9f5e7113017aa7256832fb8577f492674026134edf7442089b3b5f3"
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 75-85:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xa40b9acac25c205ead0c0dc425e88ffc7750843481317178e1b9c4bb23d1721b"
          },
          {
            "cursor": "0xc6cc506581a7262a65ba7ff09aba44a66a5276a62f2d387ed46bc40c190735f2"
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 87-97:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xa40b9acac25c205ead0c0dc425e88ffc7750843481317178e1b9c4bb23d1721b"
          },
          {
            "cursor": "0xc6cc506581a7262a65ba7ff09aba44a66a5276a62f2d387ed46bc40c190735f2"
          }
        ]
      }
    }
  }
}
