processed 13 tasks

task 1 'publish'. lines 6-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 25-25:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 27-27:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 29-29:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 31-31:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 33-33:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 8 'run-graphql'. lines 37-47:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x0379ddc2db65595af15adf79bc4201846033fa654cf11a7ed724865ca8fe47f8"
          },
          {
            "cursor": "0x42dd745babf4c233ad9dd15eae3790bc017de3df08a6f4113b056986253aa83f"
          },
          {
            "cursor": "0x52ca94d9883a0040deda657cbdcd9d663da4ebe70c428cbefc9fc9a5d43d13e9"
          },
          {
            "cursor": "0xd05e67d978406613931e8c843b51888e3a7e28f9408f955f261891abb65b0356"
          },
          {
            "cursor": "0xf167d7952b2f1dcd8a48c64dae80c22de46f08308e566ae1648f6e90ab772142"
          }
        ]
      }
    }
  }
}

task 9 'run-graphql'. lines 49-59:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x0379ddc2db65595af15adf79bc4201846033fa654cf11a7ed724865ca8fe47f8"
          },
          {
            "cursor": "0x42dd745babf4c233ad9dd15eae3790bc017de3df08a6f4113b056986253aa83f"
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 61-73:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": []
      }
    }
  }
}

task 11 'run-graphql'. lines 75-85:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x42dd745babf4c233ad9dd15eae3790bc017de3df08a6f4113b056986253aa83f"
          },
          {
            "cursor": "0x52ca94d9883a0040deda657cbdcd9d663da4ebe70c428cbefc9fc9a5d43d13e9"
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 87-97:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x42dd745babf4c233ad9dd15eae3790bc017de3df08a6f4113b056986253aa83f"
          },
          {
            "cursor": "0x52ca94d9883a0040deda657cbdcd9d663da4ebe70c428cbefc9fc9a5d43d13e9"
          }
        ]
      }
    }
  }
}
