processed 13 tasks

task 1 'publish'. lines 6-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 25-25:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 27-27:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 29-29:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 31-31:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 33-33:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 8 'run-graphql'. lines 37-47:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x2beb95f0734cd278b4521b15cdb5cad9a3091b1440e25dd08d3f39c3d9f37447"
          },
          {
            "cursor": "0x6d68db057ae76e54452d754da1494169acea6cf8f43b3899d07873526cf19192"
          },
          {
            "cursor": "0x9421a0968bfcf17c9c281448232375f2ba5fc51220aa1e3ce208aa5f074e86bc"
          },
          {
            "cursor": "0xe1f407a2914c86f35edc9991c81c75cc7280badec48197f159756fc2ce910d5d"
          },
          {
            "cursor": "0xf240619794111914613c98ee2bb445bb2fdf8a5de9625e78fb2b110610722d09"
          }
        ]
      }
    }
  }
}

task 9 'run-graphql'. lines 49-59:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x2beb95f0734cd278b4521b15cdb5cad9a3091b1440e25dd08d3f39c3d9f37447"
          },
          {
            "cursor": "0x6d68db057ae76e54452d754da1494169acea6cf8f43b3899d07873526cf19192"
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 61-73:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xf240619794111914613c98ee2bb445bb2fdf8a5de9625e78fb2b110610722d09"
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 75-85:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x6d68db057ae76e54452d754da1494169acea6cf8f43b3899d07873526cf19192"
          },
          {
            "cursor": "0x9421a0968bfcf17c9c281448232375f2ba5fc51220aa1e3ce208aa5f074e86bc"
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 87-97:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x2beb95f0734cd278b4521b15cdb5cad9a3091b1440e25dd08d3f39c3d9f37447"
          }
        ]
      }
    }
  }
}
